### ISSUE TITLE
Allow manual color schemes

### ISSUE THREAD

**Issue by danth** [danth/stylix#1]
## Description

Add a way to override the automatically-selected colors.

## Use cases

- Using a pre-made scheme such as Gruvbox
- Generated color scheme is not appealing / does not have enough variation

## Possible implementation

1. Have an option for each color (`base00` to `base0A`).
2. Hexadecimal color codes are converted to other formats inside Nix.
3. The automatic color scheme is applied to the options with `mkDefault`.

**Comment by dit7ya** [comment]
Is it possible to do manual colors now? Looking at the following, seems like it's a TODO?

https://github.com/danth/stylix/blob/f78eff2236bd8ae936aef4fba95b6769ff65624b/stylix/palette.nix#L43

**Comment by danth** [comment]
Hi, this was implemented and then made back into a TODO due to some implementation changes.

I can find some time to work on this at the weekend, as most of the code is already in place.

**Comment by Lyndeno** [comment]
For now I do this to use a manual scheme:
```nix
let
  base16Scheme = "${inputs.base16-schemes}/gruvbox-dark-hard.yaml";
in
{
  lib.stylix.colors = config.lib.base16.mkSchemeAttrs base16Scheme;
}
```

But a built in method to do so would be nice.

**Comment by danth** [comment]
@Lyndeno You should be able to use this new option now:

```nix
stylix.base16Scheme = "${inputs.base16-schemes}/gruvbox-dark-hard.yaml";
```
