### ISSUE TITLE
module template in docs

### ISSUE THREAD

**Issue by SomeGuyNamedMy** [danth/stylix#101]
i think it would be a good idea to have a module template including things like variables assigned to opacity and the hex colors, what does everyone else think?

**Comment by danth** [comment]
I think we should avoid having too much in a template, like `with` statements which might end up being unused. I would prefer a page which just explains how to create a module, like how to use `mkEnableTarget` and `config.lib.stylix.colors`, maybe referring to existing modules as an example.

**Comment by wuyoli** [comment]
Any updates on this? I would like to make a module (or more), and would really appreciate a template (or a guide if this is more appropriate).

**Comment by danth** [comment]
Working on this now.
