### ISSUE TITLE
Really slow shell (fish)

### ISSUE THREAD

**Issue by Industrial** [danth/stylix#103]
Hello. Here's my nix setup:

https://github.com/Industrial/nixos-dotfiles/blob/main/flake.nix#L82

When I enable Stylix, loading my shell (fish) takes around 5 seconds. When I disable it, it's instant. Is there something I can do about this?

**Comment by SomeGuyNamedMy** [comment]
my guess is that its in issue of the base16-fish switcher that we use for the module which doesnt look like it still gets updates, in the meantime i would suggest setting stylix.targets.fish.enable to false.

**Comment by SomeGuyNamedMy** [comment]
id imagine its an issue with the base16 repo its using, ill give it a shot once the wallpaper refactor is done

**Comment by danth** [comment]
This is unusual, I used to use Fish and this wasn't an issue. I would also expect the issue to come from the upstream repo, or the way it's installed by Stylix.

**Comment by Industrial** [comment]
I'm now using a different setup with Zellij instead of Tmux and the problem is gone..

**Comment by donovanglover** [comment]
Had the same issue for a while now and only tmux + fish is affected. Possibly related: https://github.com/danth/stylix/issues/488

**Comment by sotte** [comment]
Same, tmux + fish.

**Comment by danth** [comment]
See #488

**Comment by donovanglover** [comment]
Fixed in https://github.com/danth/stylix/pull/503
