### ISSUE TITLE
`nix flake check` fails due to upstream issue in base16.nix

### ISSUE THREAD

**Issue by montchr** [danth/stylix#104]
<https://github.com/SenchoPens/base16.nix/issues/3>

Configuring `stylix.base16` to use a path to a YAML file requires building a derivation in order to evaluate the module definitions. I can no longer run `nix flake check` successfully on `aarch64-darwin` for a `x86_64-linux` configuration after installing Stylix.

**Comment by danth** [comment]
Even after the upstream issue is fixed, Stylix will still use IFD for automatically generated colour schemes and certain modules

**Comment by SenchoPens** [comment]
I think you can close this one - I've created an issue in the base16.nix a while back and I think it is fixed.
