### ISSUE TITLE
Support for Zellij

### ISSUE THREAD

**Issue by Industrial** [danth/stylix#107]
Hi. I've started using Zellij recently and decomissioned tmux after 15 years of service 🫡

Zellij supports themes like so: https://zellij.dev/documentation/themes.html

**Comment by SomeGuyNamedMy** [comment]
will git to it once i reset my git fork after the pull requests im working on atm are merged

**Comment by Industrial** [comment]
@RANKSHANK It works but when I select text it doesn't get highlighted so it's a bit hard to select things.

**Comment by RANKSHANK** [comment]
@Industrial  Cheers for the heads up and sorry I missed this, I rarely select text in terminals.

Looks like it's due to zellij-org/zellij#1368 where the bg value in the theme is actually the highlight background.
