### ISSUE TITLE
trying to use catppuccin themes gives an error, "File not found"

### ISSUE THREAD

**Issue by TotalChaos05** [danth/stylix#115]

**Comment by danth** [comment]
Could you give some more information on how you're trying to load the theme?

**Comment by RANKSHANK** [comment]
> Could you give some more information on how you're trying to load the theme?

I'd assume it'd be the base16-schemes breaking changes https://github.com/tinted-theming/base16-schemes/commit/6af7c41a1c87f0761b27beceaf9554bb73a00868 being propagated

Means you'd need either 
`base16Scheme = "${pkgs.base16-schemes}/share/themes/catppuccin-mocha.yaml";`
if you're pinned to the newer release or 
`base16Scheme = "${pkgs.base16-schemes}/share/themes/catppuccin.yaml";`
if you're pinned to the previous release

**Comment by TotalChaos05** [comment]
does it pull directly from nixpkgs?
i thought it pulled from SenchoPens/base16.nix

**Comment by TotalChaos05** [comment]
@RANKSHANK was correct, i guess i just forgot to update my flake after i pushed the changes to nixpkgs
