### ISSUE TITLE
cursor support

### ISSUE THREAD

**Issue by realsnick** [danth/stylix#120]
will be nice for stylix to support cursor configurations
```
environment.variables.XCURSOR_SIZE = "32";
```
or 
```
home.pointerCursor = {
  gtk.enable = true;
  package = pkgs.bibata-cursors;
  name = "Bibata-Modern-Ice";
  size = 22;
};
```
and more to support xwindows and wayland

for more info:
https://gist.github.com/themattchan/55d21a524955111913afd7e1e22ce811

**Comment by danth** [comment]
What's the benefit of this over using the Home Manager options directly? Are there any apps which need a separate configuration?

**Comment by realsnick** [comment]
exactly, the benefit will be a single place for theme a cursor and its size.

i'm on hyprland and needed to setup both the examples above in order for the cursor to be the same between terminal and firefox or discord .

**Comment by Henry-Hiles** [comment]
Personally i think this is pretty useless, you can just set your cursor and the needed env vars in your home manager config, could you not?

**Comment by Henry-Hiles** [comment]
If anything, i would say this should be right in home-manager, wouldnt it fall more within that scope?

**Comment by danth** [comment]
The Home Manager module already sets `XCURSOR_SIZE` and some other environment variables for you. I don't see the benefit of adding this to Stylix unless we were generating a cursor based on the colour scheme.

**Comment by realsnick** [comment]
For me it's just about reducing the two places I change it to a single one .
