### ISSUE TITLE
error while evaluating attribute 'kdeglobals' of derivation 'stylix-kde'

### ISSUE THREAD

**Issue by TotalChaos05** [danth/stylix#125]
Not sure if this is stylix, but it worked when i disabled it. 
full trace:
https://pastebin.com/1Sj8gYk9
(not sure if i should paste the whole thing here)

it mentions kde at line 421, not sure whats happening with it.

**Comment by arguablykomodo** [comment]
Getting a very similar error. It seems that `base16.nix` is trying to parse a string with a `"` character as a hexadecimal number, but I'm not familiar enough with the codebase to properly track down the cause.

**Comment by TotalChaos05** [comment]
@arguablykomodo neither base16.nix or base16-schemes have been updated recently. is it a nixpkgs issue?

**Comment by TotalChaos05** [comment]
related issue
https://github.com/SenchoPens/base16.nix/issues/4

**Comment by arguablykomodo** [comment]
I think i found the source of the error, it seems to stem from calls to `config.lib.stylix.colors` when using a yaml base16 theme which contains comments (for example, [`helios`](https://github.com/tinted-theming/base16-schemes/blob/main/helios.yaml), [`gruvbox-dark-hard`](https://github.com/tinted-theming/base16-schemes/blob/main/gruvbox-dark-hard.yaml), and [`hardcore`](https://github.com/tinted-theming/base16-schemes/blob/main/hardcore.yaml) throw the error `attribute '"' missing`, while [`solarized-dark`](https://github.com/tinted-theming/base16-schemes/blob/main/solarized-dark.yaml), [`gruber`](https://github.com/tinted-theming/base16-schemes/blob/main/gruber.yaml), and [`cupcake`](https://github.com/tinted-theming/base16-schemes/blob/main/cupcake.yaml) don't). There must be some issue in the yaml parsing code?

**Comment by TotalChaos05** [comment]
i "fixed" it by adding 
`    base16-schemes = {
      url = github:TotalChaos05/base16-schemes;
      flake = false;
    };`
to my flake inputs and defining the scheme with 
` stylix.base16Scheme = "${base16-schemes}/catppuccin-mocha.yaml";`

all i changed in my base16-schemes fork was removing all comments

**Comment by gekoke** [comment]
Duplicate of https://github.com/danth/stylix/issues/104

**Comment by SenchoPens** [comment]
Hi, maintainer of base16.nix here! I fixed the parsing of the strings with comments after them. Before @danth updates the flake inputs of stylix, you can try it out by adding `stylix.inputs.base16.follows = "github:SenchoPens/base16.nix";` to your flake inputs.

@gekoke, this isn't duplicate of #104, but I hope I fixed that one too, but can't test myself though.

**Comment by TotalChaos05** [comment]
@SenchoPens thank you !

**Comment by danth** [comment]
Stylix should be using the fixed version by default now :)
