### ISSUE TITLE
Bat theme not working

### ISSUE THREAD

**Issue by lumikalt** [danth/stylix#132]
When trying to use `bat` to preview a file, for instance, the bat theme generated by stylix appears to error, falling back to its default theme:
~/.config/bat 
$ bat themes/base16-stylix.tmTheme 
[bat warning]: Unknown theme 'base16-stylix', using default.

**Comment by donovanglover** [comment]
Is this still an issue for you? fish autocompletes `bat --theme base16-stylix` for me. `base16` also works.

**Comment by lumikalt** [comment]
Can't test right now, gonna have to spin up a vm.

**Comment by lovesegfault** [comment]
This was a bug in `home-manager` that I fixed a while ago: https://github.com/nix-community/home-manager/pull/3886

**Comment by lumikalt** [comment]
Oh yes, I forgot this was open, still. Closing as solved.
