### ISSUE TITLE
How to view generated colours?

### ISSUE THREAD

**Issue by wanderer** [danth/stylix#14]
What is the best way to view the generated colors? Ideally I could see which base00, base01.. and their corresponding color. If there currently is not away, would it be possible to generate an HTML page that did this? Or a bash script that printed the colors?

**Comment by danth** [comment]
This command will show you the colors in JSON:

```sh
cat "$(cat /run/current-system/extra-dependencies | tr ' ' '\n' | grep 'palette.json$')"
```

I can make this file available in `/etc` for easier access and implement a HTML viewer.

**Comment by danth** [comment]
You should now be able to view the colors at `file:///etc/stylix/palette.html`

**Comment by wanderer** [comment]
Awesome thank you!
