### ISSUE TITLE
The option "fonts.packages" does not exist

### ISSUE THREAD

**Issue by Mateiadrielrafael** [danth/stylix#148]
Error:
```
  error: The option `fonts.packages' does not exist. Definition values:
       - In `/nix/store/w740vl5ciwlq5dqyy8xn0m0djn7875hh-source/stylix/nixos/fonts.nix':
           [
             <derivation nerdfonts-3.0.1>
             <derivation dejavu-fonts-2.37>
             <derivation fira-4.202>
             <derivation noto-fonts-emoji-2.038>
           ...
```

I cannot find the option [here](https://search.nixos.org/options?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=fonts.packages) either.

**Comment by Mateiadrielrafael** [comment]
It looks like this is not an issue with [nixpkgs-unstable](https://search.nixos.org/options?channel=unstable&show=fonts.packages&from=0&size=50&sort=relevance&type=packages&query=fonts.packages)

I think it's probably a good idea to hold off making this change until it gets shipped into stable nixpkgs?

**Comment by TotalChaos05** [comment]
@danth 
dont know how i missed that, could you reverse my pr?

**Comment by TotalChaos05** [comment]
wait i take that back, shouldnt you use the stable branch of stylix for stable nixpkgs?

**Comment by Mateiadrielrafael** [comment]
> wait i take that back, shouldnt you use the stable branch of stylix for stable nixpkgs?

Oh, I did not know a stable branch existed (I haven't upgraded in a long time either, I was just looking to get the updated base16 nix which doesn't always use IFD).

I ended up creating a 10loc nixos module which adds the option and assigns it to the old one.

**Comment by Mateiadrielrafael** [comment]
For anyone struggling with this, the following should do the trick:
```nix
{ lib, config, ... }: {
  options.fonts.packages = lib.mkOption {
    type = lib.types.listOf lib.types.package;
  };

  config.fonts.fonts = config.fonts.packages;
}
```
