### ISSUE TITLE
Add NixVim support

### ISSUE THREAD

**Issue by trueNAHO** [danth/stylix#153]
Add suport for [NixVim: A Neovim configuration system for nix](https://github.com/nix-community/nixvim).

Currently, enabling both `programs.neovim.enable = true;` and `programs.nixvim.enable = true;` causes the build to fail because both modules are trying to write to the same neovim configuration file. However, disabling `programs.neovim.enable = true;` does not extend `programs.nixvim`'s configuration with the colorscheme declaration, as it is not supported yet.

**Comment by danth** [comment]
This should be fairly simple to implement based on the existing colour scheme for neovim

**Comment by dwarfmaster** [comment]
I am using nixvim with stylix (config [here](https://github.com/dwarfmaster/home-nix/blob/da78839296eb3ad4ebdda25832eeda353fc48bf5/profiles/hm/programs/neovim/config.nix#L66)), so I could open a PR. However it means we need to make sure it also works on configuration without nixvim, ie with `mkIf` the option must still exists even if the condition is false.
I seem to remember we already discussed in another issue (or maybe PR, I can't find it again) about supporting modules outside of home-manager, and decided against it.
