### ISSUE TITLE
Add btop support

### ISSUE THREAD

**Issue by trueNAHO** [danth/stylix#154]
Add support for [btop: A monitor of resources](https://github.com/aristocratos/btop).

**Comment by trueNAHO** [comment]
All currently implemented btop themes are located at https://github.com/aristocratos/btop/tree/main/themes. Maybe a btop PR for base16 support must be merged first, as there seems to be no support for it yet.

**Comment by trueNAHO** [comment]
> unless btop supports configurable themes

I did not find such btop functionality.

> I think it would be easier to create our own theme

According to https://github.com/aristocratos/btop/issues/449, we replicate the schema of currently implemented themes: https://github.com/aristocratos/btop/tree/main/themes.

To resolve this issue, we need to define a good-looing base16 theme.

**Comment by RANKSHANK** [comment]
I missed linking this in #259, this should be close @danth
