### ISSUE TITLE
Finetune VSCode theme

### ISSUE THREAD

**Issue by dafitt** [danth/stylix#155]
I use the popular **Catppuccin-Mocha base16 theme** but unfortunately some color matches in the Stylix theme are off.

Buttons
![20230918_19h24m42s_grim](https://github.com/danth/stylix/assets/50248238/7cc6df67-b397-445e-aa95-39cd08a35244)
![20230918_19h25m29s_grim](https://github.com/danth/stylix/assets/50248238/0c3ac459-616f-4500-ac51-e58dbb8ae118)

Status Bar
![20230918_19h26m54s_grim](https://github.com/danth/stylix/assets/50248238/05967068-455f-46c8-85b6-a9f3849cf343)

![2023-09-18-193453](https://github.com/danth/stylix/assets/50248238/76a74335-a235-4d9c-9563-a30efd2b0295)

Preferred result:
- Button font -> darker base color
- Status bar: background -> one of the background base colors (its really annoying when so bright in dark mode)

Note: I overrided the background base colors 00 to 04 to look more gray. I did not touch the other colors.

**Comment by danth** [comment]
The buttons should be using `base00` for the text colour as this is guaranteed to contrast with the accent colours.

**Comment by danth** [comment]
> Is there any better way to extract the current base colors (to use it troughout my configuration) than with the overrides?

You can use `config.lib.stylix.colors.base00`, `config.lib.stylix.colors.base01` and so on.

**Comment by coffee-is-power** [comment]
This should have more attention, i'm having this problem no matter the colorscheme i use.

**Comment by dafitt** [comment]
I am currently using the following settings apart from the default in [modules/vscode/template.mustache](https://github.com/danth/stylix/blob/fcff15ac5ffbe81f1c66e352f3167c270d79cdab/modules/vscode/template.mustache):

```nix
programs.vscode.userSettings = {
  "workbench.colorCustomizations" = {
    "[Stylix]" = {
      "button.background" = "#${config.lib.stylix.colors.base0D}BB";
      "button.foreground" = "#${config.lib.stylix.colors.base06}";
      "button.secondaryBackground" = "#${config.lib.stylix.colors.base0E}BB";
      "button.secondaryForeground" = "#${config.lib.stylix.colors.base06}";
      "editor.selectionHighlightBackground" = "#${config.lib.stylix.colors.base04}EE";
      "editor.wordHighlightBackground" = "#${config.lib.stylix.colors.base01}00";
      "scrollbarSlider.activeBackground" = "#${config.lib.stylix.colors.base04}55";
      "scrollbarSlider.background" = "#${config.lib.stylix.colors.base03}55";
      "scrollbarSlider.hoverBackground" = "#${config.lib.stylix.colors.base04}99";
      "statusBar.background" = "#${config.lib.stylix.colors.base00}";
      "statusBar.noFolderBackground" = "#${config.lib.stylix.colors.base00}";
      "statusBar.noFolderForeground" = "#${config.lib.stylix.colors.base06}";
      "statusBarItem.remoteBackground" = "#${config.lib.stylix.colors.base00}";
    };
  };
};
```

**Comment by coffee-is-power** [comment]
@dafitt Would you mind making a pull request with those changes? If not I can try pulling something off.

**Comment by danth** [comment]
A PR with any improvements would be much appreciated :)

If not, I should be able to work on this.

**Comment by danth** [comment]
I started a branch with some of my own adjustments: #271 

Feel free to add suggestions or make pull requests on top of that branch, and we can combine them into one change before it's merged.
