### ISSUE TITLE
Hyprland config broken with latest commits upstream

### ISSUE THREAD

**Issue by panchoh** [danth/stylix#170]
Since https://github.com/hyprwm/Hyprland/commit/d537815d43c74a4e9214c4e7480c20047d297307, stylix produces an erroneous config for Hyprland:

    Config error at line 10 (/home/user/.config/hypr/hyprland.conf): Error setting value <rgb(f1f2f8)> for field <general:col.group_border_locked_active>: No such field.

With the aforementioned commit, the `col.group_border_locked_active` now falls under the `group` prefix.

**Comment by Airradda** [comment]
I came across this issue this morning and have a fix in #169. However, I don't expect a merge until the next stable release of Hyprland. For now you could simply change the input url to `github:airradda/stylix`, which I will try to keep up to date with any changes until the PR is merged.

**Comment by panchoh** [comment]
Hypand 0.31 is out, yay!
Ready your merge-o-matic :-)
