### ISSUE TITLE
Rofi theme customizability

### ISSUE THREAD

**Issue by trueNAHO** [danth/stylix#176]
# How to customize Stylix' default `rofi` theme?

For example, launching `rofi -f <FILE> -show run` with the following file successfully modifies `rofi`'s appearance:

```yaml
element {
    padding: 5px;
    spacing: 5px;
}

inputbar {
    children: [ prompt, entry ];
    padding: 10px 10px;
    spacing: 10px;
}

window {
    width: 25%;
}
```

Currently, it seems impossible to customize Stylix' default `rofi` theme without [workarounds](https://github.com/trueNAHO/dotfiles/commit/ef6813707c317775cb262a4423ca8677decefb15). For instance, defining `programs.rofi.theme` in Home Manager with the above configuration when Stylix is enabled, results in the following error because the attribute sets are not properly merged:

```nix
error:
       … while evaluating a branch condition

         at /nix/store/xjviahzwa7x51vl51kc3c1k1n1jmhpd5-source/lib/lists.nix:57:9:

           56|       fold' = n:
           57|         if n == len
             |         ^
           58|         then nul

       … while calling the 'length' builtin

         at /nix/store/xjviahzwa7x51vl51kc3c1k1n1jmhpd5-source/lib/lists.nix:55:13:

           54|     let
           55|       len = length list;
             |             ^
           56|       fold' = n:

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: The option `programs.rofi.theme' is defined multiple times while it's expected to be unique.

       Definition values:
       - In `/nix/store/3gmxlakzyn7ylnkjqz9v843dajm8b375-modules/rofi/hm.nix': "/nix/store/sxichxgwnw8igh3am8kv4rc81n91l8bq-stylix/base16-stylix.rasi"
       - In `/nix/store/kl5mlqcs9bw8v1n125sacwk1ll5qixx4-source/modules/homeManager/programs/rofi':
           {
             "#inputbar" = {
               children = [
                 {
                   _type = "literal";
           ...
       Use `lib.mkForce value` or `lib.mkDefault value` to change the priority on any of these definitions.
```

Additionnally, I have been unable to get `programs.rofi.extraConfig` to work with my intended theme modifications. But that could be my mistake.

# Related:

- https://discourse.nixos.org/t/trouble-configuring-rofi-theme-in-home-nix/16641/11
- https://github.com/danth/stylix/blob/b2f73724d11868d020207fb87fb2d9c3ae96976d/modules/rofi/hm.nix
- https://github.com/nix-community/home-manager/blob/c5c1ea85181d2bb44e46e8a944a8a3f56ad88f19/modules/programs/rofi.nix

**Comment by trueNAHO** [comment]
Additionally, should https://github.com/danth/stylix/blob/b2f73724d11868d020207fb87fb2d9c3ae96976d/modules/rofi/template.mustache declare non-color values, like paddings, in  the first place?

**Comment by danth** [comment]
I'm not sure why we're setting paddings. Does the theme look different/worse if those are removed?

**Comment by trueNAHO** [comment]
This issue should be re-opened because it is not yet resolved. https://github.com/danth/stylix/pull/179 is related to this issue, but does not resolve it.

**Comment by TotalChaos05** [comment]
how do i get rofi back to how it was before?

**Comment by trueNAHO** [comment]
> how do i get rofi back to how it was before?

The opinionated settings have been removed in https://github.com/danth/stylix/pull/179.

> is there a way to default to the original style

I assume you are referring to the state prior to https://github.com/danth/stylix/pull/179.

> make it easy to override

Customizing `rofi` is exactly what this issue addresses: https://github.com/danth/stylix/issues/176#issue-1954530751.

As long as this issue is not resolved, feel free to take inspiration from my workaround:

> Currently, it seems impossible to customize Stylix' default `rofi` theme without [workarounds](https://github.com/trueNAHO/dotfiles/commit/ef6813707c317775cb262a4423ca8677decefb15).
>
> (Source: https://github.com/danth/stylix/issues/176#issue-1954530751)
