### ISSUE TITLE
Add cursor support for Hyprland

### ISSUE THREAD

**Issue by trueNAHO** [danth/stylix#181]
> An advantage of setting the cursor via stylix is that some DE/WM can also have the cursor theme set in their respective config.
See: change in `modules/sway/hm.nix`
>
> (Source: https://github.com/danth/stylix/pull/172)

The cursor module currently does not support Hyprland.

Follows: https://github.com/danth/stylix/pull/172

**Comment by donovanglover** [comment]
Personally I change the cursor of Hyprland with [`gtk.cursorTheme`](https://github.com/donovanglover/nix-config/blob/cc1da270915f8d6e58a67e8da8fe329bd2e9a194/home/gtk.nix#L7-L10) and [`~/.icons/default/index.theme`](https://github.com/donovanglover/nix-config/blob/cc1da270915f8d6e58a67e8da8fe329bd2e9a194/home/xcursor.nix)

**Comment by danth** [comment]
In my setup, the cursor is already applied, presumably due to Stylix setting `gtk.cursorTheme`.

Is there anything specific to Hyprland which we should add on top of this?

**Comment by trueNAHO** [comment]
> In my setup, the cursor is already applied, presumably due to Stylix setting `gtk.cursorTheme`.

My bad! I did not try the latest Stylix version as I did not see the general `gtk.cursorTheme` setting in the PR.

The latest version indeed works.
