### ISSUE TITLE
After recent cursor update get invisible cursor with XWayland apps

### ISSUE THREAD

**Issue by Casul51** [danth/stylix#183]
Right after rebuilding system all XWayland apps have invisible cursor. Not mentioning default white cursor with bad size for my screen. I tried to fix it with:
```
  stylix.cursor.package = pkgs.capitaine-cursors;
  stylix.cursor.name = "capitaine-cursors";
  stylix.cursor.size = 24;
```
and
```
  home.pointerCursor.package = lib.mkForce pkgs.capitaine-cursors;
  home.pointerCursor.name = "capitaine-cursors";
  home.pointerCursor.size = 24;
  home.pointerCursor.x11.enable = true;
```

**Comment by Casul51** [comment]
WM: Hyprland

**Comment by Casul51** [comment]
Reverting back to 7a7987c7828050ef9a8ca6af07ca98485053776b and reloading DE helped

**Comment by danth** [comment]
I'm also using Hyprland and the following settings work for me:

```nix
{ pkgs, ... }:
{
  stylix.cursor = {
    package = pkgs.qogir-icon-theme;
    name = "Qogir";
  };
}
```

Would you mind testing with Qogir to see if this issue is caused by the particular cursor you're using?

**Comment by Casul51** [comment]
After another `nix flake update` and setting same cursor the issue disappear. Have no Idea what caused the issue nor how it got fixed.
The only clue I have for anyone who encounter same issue - try to set your custom cursor outside of your `home-manager.users.<username> = { pkgs,config, lib, ... }: {` coonfig
