### ISSUE TITLE
GTK3 Sidebar looks funny.

### ISSUE THREAD

**Issue by Lyndeno** [danth/stylix#187]
# Examples
## Geary
![image](https://github.com/danth/stylix/assets/13490857/50600975-da16-47a1-9236-47f5e1ce39d0)
## Gnome Tweaks
![image](https://github.com/danth/stylix/assets/13490857/abc3d1dd-038c-4681-a978-8aec961b1d79)

[Part of my stylix config](https://github.com/Lyndeno/nix-config/blob/master/common/stylix.nix)

This started a month or so ago.

**Comment by danth** [comment]
I've noticed this too.

**Comment by Henry-Hiles** [comment]
Yep, get the same issue here, quite annoying as its white text on a white BG.

**Comment by Lyndeno** [comment]
This does not occur when using gnome tweaks to change the gtk theme to adw-gtk-dark.

Also, since updating to Gnome 45, this happens in libadwaita applications too.

(I had to disable the nixos target for Gnome 45, as it fails during patching. But the home-manager targets still work)

**Comment by Lyndeno** [comment]
I guess I should probably manually specify my stylix polarity to dark since that is what I want.

Should the gtk3 module be changed to use the adw-gtk-dark theme when polarity is set to dark?

**Comment by Henry-Hiles** [comment]
It works for me now, have you updated your flake?

**Comment by TotalChaos05** [comment]
Nevermind, my gtk settings file was broken
