### ISSUE TITLE
find: ‘/run/current-system/sw/bin’: No such file or directory

### ISSUE THREAD

**Issue by DamienCassou** [danth/stylix#204]
Since commit a1cbd98719daec528538d2b7d56279ddf68f90e6, I get an error message each time I use `home-manager switch`:

```session
$ home-manager switch
...
Activating stylixLookAndFeel
find: ‘/run/current-system/sw/bin’: No such file or directory
```

This is because of this code in `modules/kde/hm.nix`:

```nix
{
    home.activation.stylixLookAndFeel =
      lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        globalPath () {
          find /run/current-system/sw/bin /usr/bin /bin \
            -maxdepth 1 -type f,l -name "$1" -print -quit
        }
     '';
}
```

The problem is that `/run/current-system/` doesn't exist on my OS (Fedora 39).

**Comment by danth** [comment]
This was meant to ignore the directory if it doesn't exist, but that's not happening here.

 I'll get it fixed as soon as possible

**Comment by DamienCassou** [comment]
Thank you very much
