### ISSUE TITLE
Include pattern matching mechanism

### ISSUE THREAD

**Issue by Mateiadrielrafael** [danth/stylix#211]
Some popular apps like discord do not yet have a stylix module. A hacky way to automate such themes is creating personal key-value map  between base16 theme names and specific themes for said applications. Said maps can then be indexed with a function like
```nix
    get = themeMap:
      themeMap.${config.lib.stylix.scheme.scheme}
        or themeMap.default.${config.stylix.polarity or "dark"}
        or themeMap.default
        or (throw "Theme ${config.lib.stylix.scheme.scheme} not found in theme map!");
```

Example usage:
```nix
  home.packages = [ discocss ];
  xdg.configFile."discocss/custom.css".source = config.satellite.theming.get themeMap;
```

I've been using this approach for a while, and think others might find it useful. Just to be clear, stylix would not provide such modules/mappings, but would simply provide the pattern matching helper.

**Comment by danth** [comment]
Although this seems useful, I don't think it should be included in Stylix because it needs a lot of manual setup and only works for certain schemes. Perhaps you could publish it as a separate repository which works alongside?
