### ISSUE TITLE
refactor(modules/plymouth): remove `substituteInPlace`

### ISSUE THREAD

**Issue by trueNAHO** [danth/stylix#225]
To properly detect breaking changes, [`modules/plymouth/nixos.nix`](https://github.com/danth/stylix/blob/a9e3ce064a778b386fb88fb152c02ae95aa2cbd2/modules/plymouth/nixos.nix) should not rely on `substituteInPlace`: https://discourse.nixos.org/t/when-to-use-substituteinplace-functions-vs-a-patch/11073.

For reference, here are the relevant sections:

https://github.com/danth/stylix/blob/a9e3ce064a778b386fb88fb152c02ae95aa2cbd2/modules/plymouth/nixos.nix#L32-L34
https://github.com/danth/stylix/blob/a9e3ce064a778b386fb88fb152c02ae95aa2cbd2/modules/plymouth/nixos.nix#L37-L39
https://github.com/danth/stylix/blob/a9e3ce064a778b386fb88fb152c02ae95aa2cbd2/modules/plymouth/nixos.nix#L66-L68

**Comment by danth** [comment]
Note that the first two examples are substituting into a file which is part of Stylix, so any breaking changes there should be predictable.
