### ISSUE TITLE
The release 23.11 branch has an option that does not exist in home-manager 23.11

### ISSUE THREAD

**Issue by vinicius507** [danth/stylix#241]
I've gotten the following error when trying to build my NixOS configuration today:

```
       error: The option `home-manager.users.vini.programs.bemenu' does not exist. Definition values:
       - In `/nix/store/rngnay1xm6n0r89iaj7a9hjjsd7dwmml-modules/bemenu/hm.nix':
           {
             _type = "if";
             condition = true;
             content = {
               settings = {
           ...
```

Looking at home-manager git history it was added after the 23.11 release: https://github.com/nix-community/home-manager/commits/master/modules/programs/bemenu.nix

**Comment by vinicius507** [comment]
Mistake on my part: forgot to update input after changing to `release-23.11` branch 🥲

**Comment by trueNAHO** [comment]
Related: https://github.com/danth/stylix/commit/423c819d7702a78c52a80df7721d6c04bcbf2eab

**Comment by hyperboly** [comment]
I'm getting the same issue. How was this fixed?

Running `nix flake update` did not help

**Comment by danth** [comment]
See #379
