### ISSUE TITLE
Add to home-manager as a module

### ISSUE THREAD

**Issue by DamienCassou** [danth/stylix#25]
As a home-manager user, I would like to just add `programs.stylix = {enable=true;...}` to my configuration.

**Comment by danth** [comment]
> I too wish we had separate nixos and home-manager modules.

This is being worked on in #23. It's mostly finished and will be merged soon

**Comment by DamienCassou** [comment]
Now that #23 has been merged, is any more work planned around this? I feel that the README could contain an example of how to setup stylix with home-manager on a non-NixOS distro.

**Comment by danth** [comment]
I agree we should add an example for that use case. It hasn't been tested on non-NixOS yet, however I would expect it to work at least to some extent. It would be great if someone with experience using Home Manager on another distro could set it up and provide feedback :)

If your Home Manager configuration is in a flake, you should be able to import `homeManagerModules.stylix` similar to the example for NixOS.

**Comment by DamienCassou** [comment]
@danth I tried and I got an issue: https://github.com/danth/stylix/issues/28.

**Comment by DamienCassou** [comment]
Here is a working configuration:

```nix
{pkgs, ...}@args:

let
  base16 = import ../../base16;
  palette-generator = pkgs.callPackage ../../stylix/palette-generator { };
in
{
  stylix.image = pkgs.fetchurl {
    url = "https://www.pixelstalk.net/wp-content/uploads/2016/05/Epic-Anime-Awesome-Wallpapers.jpg";
    sha256 = "enQo3wqhgf0FEPHj2coOCvo7DuZv+x5rL/WIo4qPI50=";
  };

  imports = [
    (import ../../stylix/stylix/hm {
      inherit palette-generator;
      base16 = base16 args;
    })
  ];
}
```

Do you want a PR for the README?

**Comment by danth** [comment]
I already added an example for Home Manager + Flakes; I've been trying to keep the documentation to flakes only for clarity, but if you think the non-flake version is helpful then please do go ahead with a PR.

**Comment by DamienCassou** [comment]
I wouldn't have focused only on flakes while they are experimental.

**Comment by Mateiadrielrafael** [comment]
Thanks for solving this!
