### ISSUE TITLE
kde: conflict with plasma-manager

### ISSUE THREAD

**Issue by Noodlez1232** [danth/stylix#250]
The [plasma-manager home-manager "extension"](https://github.com/pjones/plasma-manager) overwrites some of the files that are used by stylix (specifically "kcminputrc", "kded5rc", and "kdeglobals").
At first I thought of opening up the issue there, but I think it'd be worthwhile to look into using this to do our KDE management instead, since it might be easier later on to add options to stylix (and also compatibility because I could see other people using both at the same time).

This may also be related to pull request #142, since its inclusion would remove the need for "kdeglobals"

**Comment by Noodlez1232** [comment]
I'm actually working on this now, but I was wondering if there were to be any interest in this if I were to open up a pull request, or would it be not needed?
I think one of the main problems is that plasma-manager makes an option called "plasma.enable" that we could possibly use for stylix's mkEnableTarget.

**Comment by Noodlez1232** [comment]
As it turns out, after doing some more poking around, this is a bug with *my* configuration not with stylix. I'm closing it, but I will probably open another one with the possibility of using plasma-manager still, since I think it's still useful to avoid some of the messiness of the module. For now I'll start my improvements there, and then probably come here again with some suggestions on that.

**Comment by danth** [comment]
If we *replaced* the module with plasma-manager, then everyone would be required to have that installed to get theming. We could try something similar to the situation with NeoVim, where there are separate targets for the built in Home Manager module and NixVim.
