### ISSUE TITLE
k9s skin option has been renamed

### ISSUE THREAD

**Issue by svenihoney** [danth/stylix#255]
Using k9s and stylix gives me the following warning:
```
trace: warning: sven profile: The option `programs.k9s.skin' defined in `/nix/store/hkzfi73ddw7b54m50akpq4h322zn44c3-modules/k9s/hm.nix' has been renamed to `programs.k9s.skins.skin'.
```
Perhaps it is possible to adapt the path inside stylix to adapt to the new option name.

**Comment by svenihoney** [comment]
My bad, was wrong version of stylix.

**Comment by danth** [comment]
Linked the pull request for future reference.
