### ISSUE TITLE
stylix.fonts.emoji breaks wezterm emoji

### ISSUE THREAD

**Issue by KiaraGrouwstra** [danth/stylix#257]
`stylix.fonts.emoji` seems currently only used in wezterm.
however, setting this for some fonts like `stylix.fonts.emoji = { pkgs.twemoji-color-font; name = "Twitter Color Emoji"; }`, seems to in fact break emoji on wezterm, instead falling back to `noto-fonts-monochrome-emoji` instead.

**Comment by RANKSHANK** [comment]
Looks related to wez/wezterm#4713

**Comment by KiaraGrouwstra** [comment]
thanks, let's close in favor of that one then
