### ISSUE TITLE
Change specification for selection background

### ISSUE THREAD

**Issue by danth** [danth/stylix#277]
## Current specification

According to the current version of the [style guide](https://danth.github.io/stylix/styling.html#general-colors), `base03` should be used as the background color for selected items. It is not specified what to use as the foreground color.

In Sakura - a light theme, using `base05` as the foreground causes bad contrast.

![Screenshot of Sakura with bad contrast](https://github.com/danth/stylix/assets/28959268/e72b9bc0-e4b9-4c75-bb92-56142240a496)

If we change the foreground to `base00`, this is improved.

![Screenshot of Sakura with good contrast](https://github.com/danth/stylix/assets/28959268/157aaf6d-b320-49d0-a5ae-31d3d434efd3)

However, `base00` as the foreground causes bad contrast with Catppuccin Frappe - a dark theme.

![Screenshot of Catppuccin Frappe with bad contrast](https://github.com/danth/stylix/assets/28959268/57a9a04a-e815-4a60-be0c-a14bafd06a6b)

This is improved if we use the original setting of `base05`.

![Screenshot of Catppuccin Frappe with good contrast](https://github.com/danth/stylix/assets/28959268/0303d035-a7c7-43ef-aaaa-859a382ecb85)

## Suggested specification

I suggest changing the background to `base02`. This looks correct under both schemes, and is listed in the [original base16 specification](https://github.com/chriskempson/base16/blob/main/styling.md).

![Screenshot of Sakura with new background](https://github.com/danth/stylix/assets/28959268/c602c8a8-41a9-4abf-8ad4-a9f6885870c7)

![Screenshot of Catppuccin Frappe with new background](https://github.com/danth/stylix/assets/28959268/ee30eefd-b206-4ccd-8edb-818adf02383c)

This may require some changes to existing modules which are following the old specification.

**Comment by rice-cracker-dev** [comment]
maybe give an option for user to use a base16 color instead of a predefined one?
