### ISSUE TITLE
Where to find the HTML theme file in non-NixOS?

### ISSUE THREAD

**Issue by DamienCassou** [danth/stylix#30]
The README says:

> After rebuilding, the full theme can be previewed at file:///etc/stylix/palette.html in a web browser.

On non-NixOS systems, the file can't be added to `/etc/`. Where is it?

**Comment by DamienCassou** [comment]
Seems like it is in ~~/.config/stylix~. Do you want a PR improving the README?

**Comment by danth** [comment]
Yeah, `file:///home/«user»/.config/stylix/palette.html` is the Home Manager equivalent. (Technically `$XDG_CONFIG_HOME` could be different, but it is almost always `.config`.)

Please go ahead with a PR :+1:
