### ISSUE TITLE
Wallpaper withBinaryFile does not exist (No such file or directory)

### ISSUE THREAD

**Issue by ddogfoodd** [danth/stylix#324]
I just updated to the latest in nixos-unstable, now stylix palette creation fails as it doesn't seem to find my wallpaper.

I get the following error:
```
Processing /home/user/.config/nixos/wallpaper.jpg
palette-generator: /home/user/.config/nixos/wallpaper.jpg: withBinaryFile: does not exist (No such file or directory)
CallStack (from HasCallStack):
  error, called at Stylix/Main.hs:15:26 in main:Main
```

I made sure the file (`/home/user/.config/nixos/wallpaper.jpg`) still exists.
I am not sure, but I update regularly so maybe the error was introduced with [this recent commit](https://github.com/danth/stylix/commit/a0bdd9c15b23a5db48d29afe3b238333605c357c) changing wallpaper path handling.

I would like to test if it does but am not sure yet if there is a convenient way to revert back to before this commit with Nix.
If you know how to do it, drop me a hint and I will try it out.

**Comment by trueNAHO** [comment]
> I would like to test if it does but am not sure yet if there is a convenient way to revert back to before this commit with Nix.
> If you know how to do it, drop me a hint and I will try it out.

To automate the procecdure, you could write a small script that runs [`git bisect run`](https://git-scm.com/docs/git-bisect) on Stylix, and on each iteration you verify whether your NixOS or Home Manager configuration still works.

**Comment by wanderer** [comment]
I also am having this problem

**Comment by trueNAHO** [comment]
Does https://github.com/danth/stylix/pull/329 resolve the issue?

**Comment by trueNAHO** [comment]
> > To automate the procecdure, you could write a small script that runs [`git bisect run`](https://git-scm.com/docs/git-bisect) on Stylix, and on each iteration you verify whether your NixOS or Home Manager configuration still works.
>
> Does this work with nix flakes installation or just with the cloned git repo?

For example, you could specify the commit hash as:

https://github.com/danth/stylix/blob/b6dbe9ac5d57d27d5620445f20cad2c353089f86/flake.nix#L10

Personally, I prefer to do this with a local clone:

```diff
- inputs.stylix.url = "github:danth/stylix";
+ inputs.stylix.url = "git+file:/path/to/stylix";
```

In `/path/to/stylix`, I simply `git checkout` whatever commit I want, and then I `nix flake lock --update-input stylix` in the `flake.nix` file that imports it.

> Does #329 resolve the issue?

Alternatively, you could this PR with:

```diff
- inputs.stylix.url = "github:danth/stylix";
+ inputs.stylix.url = "github:trueNAHO/stylix/fix-stylix-palette-do-not-escape-spaces-in-wallpaper-path";
```

**Comment by feathecutie** [comment]
> Does #329 resolve the issue?

I'm having the exact same issue, and for me, that PR resolved it.

**Comment by danth** [comment]
The commit which caused this has been reverted for now.

**Comment by zDyanTB** [comment]
If you put "" around the image path, it returns that same error, just in case anyone face it
