### ISSUE TITLE
doc: replace tracking issues

### ISSUE THREAD

**Issue by trueNAHO** [danth/stylix#331]
> In fact, it may be more appropriate to use [milestones](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones) rather than tracking issues at all.
>
> (Source: https://github.com/danth/stylix/pull/325#issuecomment-2035527982)

The [tracking issue format](https://github.com/danth/stylix/pull/325) is inspired by [Rust's project management](https://github.com/rust-lang/rust/labels/C-tracking-issue). Unfortunately, I was unable to find an explicit clarification on why they have not adopted the relatively new GitHub Milestones or GitHub Projects formats yet.

IMHO, project management tools beyond (tracking) issues and PRs are overkill and a waste of time in nearly every single-developer side project. However, Stylix is slowly attracting more contributors, and the number of feature, bug, refactor, and performance requests increases likewise. Despite the project having "only" 79 open issues (at the time of writing), it would take an enormous amount of time (in FOSS context) to figure out what overall direction the project is taking due to conflicting or very similar requests. This makes it harder to understand and discuss the overall optimal direction of the project.

I suggest adopting GitHub Projects or GitHub Milestones for Stylix, despite having no practical experience with them yet.

A somewhat elaborate comparison of GitHub Milestones and GitHub Projects can be found at: https://stackoverflow.com/questions/39591795.

Considering Stylix's primarily rolling release development model, I cannot think of any good examples for using GitHub Milestones, other than major (breaking) changes that end-users and developers may want to look forward to; although it would in most cases merely duplicate the GitHub Projects and waste additional effort in project management. As pointed out earlier, it might be beneficial to replace every currently existing tracking issue with an individual GitHub Project.

**Comment by trueNAHO** [comment]
> As pointed out earlier, it might be beneficial to replace every currently existing tracking issue with an individual GitHub Project.

Upon reconsideration, I prefer a simpler development environment similar to the [Linux Kernel email process](https://www.kernel.org/doc/html/latest/process/submitting-patches.html). The GitHub idiomatic equivalent would be issues and PRs.

**Comment by danth** [comment]
I agree, there is no problem with the way things are organised right now.

**Comment by danth** [comment]
There's now [sub issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/adding-sub-issues), which seem appropriate for this.

**Comment by trueNAHO** [comment]
> There's now [sub issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/adding-sub-issues), which seem appropriate for this.

I would have to think longer about this, but here are my current thoughts on GitHub's sub-issue feature.

AFAIK, sub-issues form a tree. However, since most of our GitHub issues are highly interconnected and unstructured, we need a graph. Sub-issues cannot represent this, and I am unsure how time-consuming it is to re-parent sub-issues when we decide to change how issues get resolved.

One alternative would be to separate unstructured and structured discussions into GitHub discussions and GitHub issues, as done by Ghostty:

> Users are not allowed to create Issues directly in this repository - we ask that you create a Discussion first.
>
> Unlike some other projects, Ghostty does not use the issue tracker for discussion or feature requests. Instead, we use GitHub discussions for that. Once a discussion reaches a point where a well-understood, actionable item is identified, it is moved to the issue tracker. This pattern makes it easier for maintainers or contributors to find issues to work on since every issue is ready to be worked on.
>
> This approach is based on years of experience maintaining open source projects and observing that 80-90% of what users think are bugs are either misunderstandings, environmental problems, or configuration errors by the users themselves. For what's left, the majority are often feature requests (unimplemented features) and not bugs (malfunctioning features). Of the features requests, almost all are underspecified and require more guidance by a maintainer to be worked on.
>
> Any Discussion which clearly identifies a problem in Ghostty and can be confirmed or reproduced will be converted to an Issue by a maintainer, so as a user finding a valid problem you don't do any extra work anyway. Thank you.
>
> -- [mitchellh, "Why users cannot create Issues directly"](https://www.github.com/ghostty-org/ghostty/issues/3558)

Considering the current number of open issues, converting to this structure is rather unfeasible and does not add much value. Once the [Roadmap](https://github.com/danth/stylix/issues/534) is completed, the number of open issues might be low enough that we could re-consider this approach.

Conclusion: We should stick with the current issue and tracking issue approach for now.

**Comment by danth** [comment]
I was suggesting more that we simply use sub issues to format the tracking issues, rather than listing links in the body.

As you say, there's no need to change the way we manage things.

(And little value in going back to reformat old issues)
