### ISSUE TITLE
stylix plymouth get 404 for nix-snowflake.svg

### ISSUE THREAD

**Issue by coldelectrons** [danth/stylix#334]
Recently I tried using a config flake that builds a NixOS image, and it fails thusly:
```
error: builder for '/nix/store/q8kb6c881sbgszfxbi73i4vfwp918glp-nix-snowflake.svg.drv' failed with exit code 1;
       last 7 log lines:
       >
       > trying https://raw.githubusercontent.com/NixOS/nixos-artwork/master/logo/nix-snowflake.svg
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       >   0    14    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
       > curl: (22) The requested URL returned error: 404
       > error: cannot download nix-snowflake.svg from any mirror
       For full logs, run 'nix log /nix/store/q8kb6c881sbgszfxbi73i4vfwp918glp-nix-snowflake.svg.drv'.
error: 1 dependencies of derivation '/nix/store/i838vqy1xn96ll9kbp6df03jk2i0hq5f-stylix-plymouth.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ha8xhw5ajhgrr3dg93yi1xgw44gizvfc-plymouth-themes.drv' failed to build
```

Looking at the master branch  of  `nixos-artwork`, it seems that logo has become two variants, coloured and white.
And if my interpretation of git commits are correct, files were renamed 17 hours ago, not long before I started my build. :)

**Comment by trueNAHO** [comment]
> Looking at the master branch of `nixos-artwork`, it seems that logo has become two variants, coloured and white.
> And if my interpretation of git commits are correct, files were renamed 17 hours ago, not long before I started my build. :)

Thanks for the digging. This made it a lot easier for me.

Does https://github.com/danth/stylix/pull/335 resolve the issue?

**Comment by danth** [comment]
In the long term we may wish to use the logo from `pkgs.nixos-icons` rather than downloading a separate copy.

**Comment by sbuller** [comment]
This issue still affects release-23.11. Is there any appetite to support that branch?

**Comment by trueNAHO** [comment]
> This issue still affects release-23.11. Is there any appetite to support that branch?

This has already been requested in https://github.com/danth/stylix/pull/335#issuecomment-2082812402.

I opened a tracking issue for this: https://github.com/danth/stylix/issues/356.
