### ISSUE TITLE
stylix plymouth get ERROR  for nix-snowflake.svg

### ISSUE THREAD

**Issue by panchoh** [danth/stylix#337]
Hi!

A slight variation of #334, as of latest commit:

```
nixos-rebuild switch
building the system configuration...
error: builder for '/nix/store/py07vcw9x9wwvpi0ipcgp62mdqv7lgc9-nix-snowflake-colours.svg.drv' failed with exit code 1;
       last 7 log lines:
       >
       > trying https://raw.githubusercontent.com/NixOS/nixos-artwork/f84c13adae08e860a7c3f76ab3a9bef916d276cc/logo/nix-snowflake-colours.svg
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       > 100 11801  100 11801    0     0  53532      0 --:--:-- --:--:-- --:--:-- 53398
       > substituteStream(): ERROR: pattern 141.5919 doesn't match anything in file '/nix/store/71qx9gdwmc3yhajs2s5wacndk8fa7k77-nix-snowflake-colours.svg'
       > /nix/store/zykyv2faxz6s1l2pdn6i7i5hb5r5wri6-stdenv-linux/setup: line 131: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/py07vcw9x9wwvpi0ipcgp62mdqv7lgc9-nix-snowflake-colours.svg.drv'.
error: 1 dependencies of derivation '/nix/store/av3821pyvgi1w5ywkj13zr2n4dvp1dcn-stylix-plymouth.drv' failed to build
error: 1 dependencies of derivation '/nix/store/0dcw2icg7xmlwphnlgfsrx4zbs673kdv-plymouth-themes.drv' failed to build
error: 1 dependencies of derivation '/nix/store/f5p9gyzghhpk8sb3z3rfx14vljbi7x6v-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/5n3j532m1yglqvqwxwvf0hhvxvg7dnbs-plymouth-initrd-plugins.drv' failed to build
error: 1 dependencies of derivation '/nix/store/2a3mw3jqak3rmmkmp0js5lb4n2lklvn8-plymouth-initrd-themes.drv' failed to build
error: 1 dependencies of derivation '/nix/store/cvnzipkqg0chm044p2m3w2jvlkz5lwqw-nixos-system-krypton-24.05.20240408.4cba8b5.drv' failed to build
```
For reference, see my [flake](https://github.com/panchoh/nixos)

**Comment by trueNAHO** [comment]
Does https://github.com/danth/stylix/pull/338 resolve the issue?

**Comment by panchoh** [comment]
> Does #338 resolve the issue?

I get these errors:

```
warning: Git tree '/home/pancho/sandbox/panchoh/nixos' is dirty
warning: updating lock file '/home/pancho/sandbox/panchoh/nixos/flake.lock':
• Updated input 'stylix':
    'github:danth/stylix/406f793045ce82689194273cb7e7c4ad0fec530c' (2024-04-11)
  → 'github:trueNAHO/stylix/7877804dae9e6e0fd8986b8fddb4daffec1ea176' (2024-04-11)
warning: Git tree '/home/pancho/sandbox/panchoh/nixos' is dirty
building the system configuration...
warning: Git tree '/home/pancho/sandbox/panchoh/nixos' is dirty
error: hash mismatch in fixed-output derivation '/nix/store/wkhxq9lf2lwpggfkal7g59wjybs2vw3q-nix-snowflake-colours.svg.drv':
         specified: sha256-4+MWdqESKo9omd3q0WfRmnrd3Wpe2feiayMnQlA4izU=
            got:    sha256-pHYa+d5f6MAaY8xWd3lDjhagS+nvwDL3w7zSsQyqH7A=
error: 1 dependencies of derivation '/nix/store/n5xswj1kb4na5jgin4i7xw9ijgjan7s6-stylix-plymouth.drv' failed to build
error: 1 dependencies of derivation '/nix/store/q79vq8cl37yjzqm02fa4q1lxhxl6c3af-plymouth-themes.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ldl36pg59j0pqac14zvz2k8a8ym0g9zz-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/qdybnhziq3l2dlzi9cgzwp678c82kazn-plymouth-initrd-plugins.drv' failed to build
error: 1 dependencies of derivation '/nix/store/cax7nj7y5s61dm7p5vy561h2nis42wqz-plymouth-initrd-themes.drv' failed to build
error: 1 dependencies of derivation '/nix/store/kp9kvl48llbdwwb2j6c0n01zf1v6dzax-nixos-system-krypton-24.05.20240408.4cba8b5.drv' failed to build
```

**Comment by trueNAHO** [comment]
> I get these errors:
>
> ```
> warning: Git tree '/home/pancho/sandbox/panchoh/nixos' is dirty
> warning: updating lock file '/home/pancho/sandbox/panchoh/nixos/flake.lock':
> • Updated input 'stylix':
>     'github:danth/stylix/406f793045ce82689194273cb7e7c4ad0fec530c' (2024-04-11)
>   → 'github:trueNAHO/stylix/7877804dae9e6e0fd8986b8fddb4daffec1ea176' (2024-04-11)
> warning: Git tree '/home/pancho/sandbox/panchoh/nixos' is dirty
> building the system configuration...
> warning: Git tree '/home/pancho/sandbox/panchoh/nixos' is dirty
> error: hash mismatch in fixed-output derivation '/nix/store/wkhxq9lf2lwpggfkal7g59wjybs2vw3q-nix-snowflake-colours.svg.drv':
>          specified: sha256-4+MWdqESKo9omd3q0WfRmnrd3Wpe2feiayMnQlA4izU=
>             got:    sha256-pHYa+d5f6MAaY8xWd3lDjhagS+nvwDL3w7zSsQyqH7A=
> error: 1 dependencies of derivation '/nix/store/n5xswj1kb4na5jgin4i7xw9ijgjan7s6-stylix-plymouth.drv' failed to build
> error: 1 dependencies of derivation '/nix/store/q79vq8cl37yjzqm02fa4q1lxhxl6c3af-plymouth-themes.drv' failed to build
> error: 1 dependencies of derivation '/nix/store/ldl36pg59j0pqac14zvz2k8a8ym0g9zz-etc.drv' failed to build
> error: 1 dependencies of derivation '/nix/store/qdybnhziq3l2dlzi9cgzwp678c82kazn-plymouth-initrd-plugins.drv' failed to build
> error: 1 dependencies of derivation '/nix/store/cax7nj7y5s61dm7p5vy561h2nis42wqz-plymouth-initrd-themes.drv' failed to build
> error: 1 dependencies of derivation '/nix/store/kp9kvl48llbdwwb2j6c0n01zf1v6dzax-nixos-system-krypton-24.05.20240408.4cba8b5.drv' failed to build
> ```

Could you update your `github:trueNAHO/stylix` input: https://github.com/danth/stylix/pull/338#issuecomment-2050374000?

**Comment by panchoh** [comment]
> Could you update your `github:trueNAHO/stylix` input: [#338 (comment)](https://github.com/danth/stylix/pull/338#issuecomment-2050374000)?

It works like a charm. Very much appreciated, @trueNAHO !
