### ISSUE TITLE
alacritty: ineligible text inside comments

### ISSUE THREAD

**Issue by xokdvium** [danth/stylix#341]
I'm using [catppuccin-macchiato.yaml](https://github.com/tinted-theming/base16-schemes/blob/main/catppuccin-macchiato.yaml) theme.
The terminal is alacritty. I've noticed that some text in the console is too dark. This occurs for commented text and some other tools like `hx --health` (in the lsp column paths to `/nix/store` are unreadable):

![image](https://github.com/danth/stylix/assets/145775305/b02e705f-5360-4e89-b25d-4c8bf0c3a8d5)

Inline comments also are indistinguishable from background (the actual command is `echo "hello" # asdfasdfasdf`)

![image](https://github.com/danth/stylix/assets/145775305/739f3545-71b9-4390-8039-40e8a96f493e)

**Comment by trueNAHO** [comment]
Related: https://github.com/danth/stylix/issues/249

**Comment by danth** [comment]
How does this look without the transparent background?

**Comment by xokdvium** [comment]
Removing transparency does not seem to make a huge difference. The text still has very poor contrast with a dark background.
Seems like this is a problem with alacritty specifically. With wezterm colors seem much more reasonable. 

Alacritty:
![image](https://github.com/danth/stylix/assets/145775305/dc4634be-7da4-42ab-b1aa-bc35c5a60766)

Wezterm:
![image](https://github.com/danth/stylix/assets/145775305/c5d6e5e1-c184-40ff-93fd-ad05d29a98aa)

I think the issue is with the upstream base16-alacritty template:

Generated alacritty theme has really badly misconfigured highlight colors:

```toml
[colors.bright]
black = '0x494d64'
red = '0xf5a97f'
green = '0x1e2030'
yellow = '0x363a4f'
blue = '0x5b6078'
magenta = '0xf4dbd6'
cyan = '0xf0c6c6'
white = '0xb7bdf8'
```

The supposedly green color is actually 0x1e2030, which is dark blue... 
`base16-alacritty` repo seems quite a bit [borked](https://github.com/aarowill/base16-alacritty/blob/c95c200b3af739708455a03b5d185d3d2d263c6e/templates/default.mustache#L29-L37) and does not conform to base16/stylix guidelines.
