### ISSUE TITLE
nixos-icons: white.svg has been renamed to nixos-white.svg

### ISSUE THREAD

**Issue by geordieshaun** [danth/stylix#342]
Hi,

first timer and new to nix and linux, it appears that "logo/white.svg" is now "logo/nixos-white.svg" in nixos-icons-unstable:

`> substitute(): ERROR: file 'logo/white.svg' does not exist`

`ls /nix/store/8gzig2c39hd1h1vf0rqvadw11vy3kxas-source/logo
font                      nixos.text.svg             nix-social-preview.svg
nixos-social-preview.png  nixos-white.png            parametric-flake.scad
nixos-social-preview.svg  nixos-white.svg            README.md
nixos.svg                 nix-snowflake-colours.svg  simple-flake.scad
nixos.svg.png             nix-snowflake-white.svg
nixos-text-below.svg      nix-social-preview.png`

Cheers :-)

**Comment by danth** [comment]
Hi, is this affecting the `nixos-icons` target or the `plymouth` target?

(You can check this by setting `stylix.targets.nixos-icons.enable = false` and see if the issue still occurs.)

**Comment by danth** [comment]
Nevermind, just saw the PR fixing this.
