### ISSUE TITLE
Error with stylix.image: not of type 'path or package convertible to it

### ISSUE THREAD

**Issue by cachedpotato** [danth/stylix#345]
Hello,
I'm a newbie NixOS user and I've been trying to set up stylix but encountering some problems.
I first downloaded an image in a seperate folder (which is one level above where stylix.nix is located) and set stylix.image like so: 
```nix
stylix = {
  image = ../wallpaper1.jpg;
....
```
when I tried to rebuild my home-manager I got this error:
```
       error: A definition for option `stylix.image' is not of type `path or package convertible to it'. Definition values:
       - In `<unknown-file>': null
```  
I then tried to change my stylix.image using fetchurl:
```nix
stylix = {
  image = pkgs.fetchurl{
    url = "https://link/to/wallpaper.jpg
    sha256 = "";
....
``` 
which gave me the same error. I don't think I did anything noteworthy regarding this error, the following is pretty much all I can think of that may be "noteworthy":
- I first downloaded the jpg file in my Downloads folder, then moved to a directory which has all my nixos related config files (flakes, home-manager stuff)
- and I have my config directory uploaded to a private github repo
- I pushed all my changes (including the new stylix.nix file I just created) before I did home-manager switch --flake .
- the wallpaper file is rather big (14MB if I read it correctly, idk why it's this big)

I feel like I'm missing extremely basic here but I really don't know what. Any help would be greatly appreciated.

Thanks!

**Comment by cachedpotato** [comment]
I forgot to import my stylix.nix into my main default.nix home-manager file... I'm dumb.

**Comment by chris-kruining** [comment]
at least you are not alone. I made the same mistake.

Though in our defense, getting an error that the setting you just made before you run the build is configured wrong, does not really hint to: the settings are missing altogether :P

**Comment by trueNAHO** [comment]
> Though in our defense, getting an error that the setting you just made before you run the build is configured wrong, does not really hint to: the settings are missing altogether :P

Related: https://github.com/danth/stylix/issues/200
