### ISSUE TITLE
Option to change font size

### ISSUE THREAD

**Issue by jevy** [danth/stylix#35]
I would like to override the font size in `/modules/sway/hm.nix` what's the best practice to do so? Is it a nix override?

**Comment by danth** [comment]
Unfortunately it's not possible to change that without editing the file directly.

I will add an option so that you can set `stylix.targets.sway.fontSize` to your preferred size.

**Comment by danth** [comment]
Overlays only work for packages, NixOS/Home Manager are using modules for configuration.

The module equivalent of overrides would be `mkForce`, but it can't override `let` bindings, so you have to apply `mkForce` to every place where the value is used instead. In the case of Sway this would be `wayland.windowManager.sway.config.fonts.size` and `lib.stylix.sway.bar.fonts.size`, but it gets more complicated if the value is repeated in lots of places.

I suppose another route is to disable `stylix.targets.sway` and import your own copy of the module in its place, which would allow you to edit the code freely. Of course that would mean that you don't receive updates if the original module is changed.

**Comment by dwarfmaster** [comment]
In general I think we need to figure out a way to handle fontsizes, to avoid this kind of hardcoding. Maybe creating creating some sort of nomenclature for font sizes that the user could set, so that the different modules could pick the relevant size automatically :thinking:
