### ISSUE TITLE
plymouth: backport URL locking

### ISSUE THREAD

**Issue by trueNAHO** [danth/stylix#356]
# About 

This is a tracking issue for backporting the URL locking.

# Steps 

- [X] https://github.com/danth/stylix/pull/361

# Unresolved Questions 

- [x] Are there any other associated commits to be backported as well?

**Comment by trueNAHO** [comment]
> Looking at this I think we need to backport the following two commits:
> 
> [c630a7d](https://github.com/danth/stylix/commit/c630a7d3ee4530e6a0e20ddf45ad813fc8b6da1b) [83866ed](https://github.com/danth/stylix/commit/83866ed8800ed39519a79ea30b18c8eb21f26080)

Looks about right. Could you maybe do the backporting?

**Comment by danth** [comment]
See the referenced PR.

**Comment by trueNAHO** [comment]
Closed by https://github.com/danth/stylix/pull/361.
