### ISSUE TITLE
value is a string with context while a set was expected

### ISSUE THREAD

**Issue by smahidev** [danth/stylix#374]
stylix.base16Scheme won't accept path of yaml as string bellow the example :
 
stylix.base16Scheme = "${pkgs.base16-schemes}/share/themes/tokyo-night-dark.yaml";

**Comment by Cody-W-Tucker** [comment]
Can you share more of your config or more of the issue? I set my the same way and have no issues.

`stylix.base16Scheme = "${pkgs.base16-schemes}/share/themes/tomorrow-night.yaml";`

**Comment by smahidev** [comment]
sorry i switch to nix-colors.
