### ISSUE TITLE
home manager bemenu option missing

### ISSUE THREAD

**Issue by AdamDunmore** [danth/stylix#375]
Im attempting to install stylix on my nixos system. 

When I rebuild my system with this config:

```
{ pkgs, stylix, ... }:

{
    stylix = {
        image = ../../assets/wallpaper.png;
    };
}
```

I get this error:
```
error: The option `home-manager.users.adam.programs.bemenu' does not exist. Definition values:
       - In `/nix/store/q2sjkd85aa9q5bf22gxg0m9ks3a9xw45-modules/bemenu/hm.nix':
```

I dont use bemenu and nor do I have it installed. I have tried to install it but the error persists.

Any help would be great.

More info can be provided however I am running Nixos 21.14 with Hyprland.

Thanks

**Comment by trueNAHO** [comment]
> I get this error:
>
> ```
> error: The option `home-manager.users.adam.programs.bemenu' does not exist. Definition values:
>        - In `/nix/store/q2sjkd85aa9q5bf22gxg0m9ks3a9xw45-modules/bemenu/hm.nix':
> ```
>
> I dont use bemenu and nor do I have it installed. I have tried to install it but the error persists.

I assume there some sort of version mismatch. Consider taking a look at https://github.com/danth/stylix/issues/241.

> More info can be provided however I am running Nixos 21.14 with Hyprland.

Could you share your input versions?

**Comment by AdamDunmore** [comment]
Super sorry. Missed this when checking for duplicate issues. 

I have I weird setup that gives me odd inputs for my hyprland package. I've not been able to fix it so I left it and forgot.

Thanks for the help.

**Comment by AdamDunmore** [comment]
I never managed to fix the issue and assumed it was an issue with hyprland however since switching to sway I continue to run into issues. Im getting the same error. Any help would be great.
