### ISSUE TITLE
Cannot find colorscheme 'base16-stylix'

### ISSUE THREAD

**Issue by WJehee** [danth/stylix#378]
Hey, love the project pretty much everything worked straight out of the box for me, but I came across this one issue.
I have 2 machines running the same configuration, but on 1 of the machines i get the following error when opening neovim:

```
Error detected while processing /home/user/.config/nvim/init.lua:
E5113: Error while calling lua chunk: vim/_editor.lua:0: /home/user/.config/nvim/init.lua..nvim_exec2() called at /home/user/.config/nvim/init.lua:0../nix/store/ccv39rvxf4swj4qnspkzk9k0np384z88-nvim
-init-home-manager.vim, line 2: Vim(colorscheme):E185: Cannot find color scheme 'base16-stylix'
stack traceback:
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        /home/user/.config/nvim/init.lua:1: in main chunk
```
        
 I have already verified that all the files are present, there is a /nix/store/.../colors/base16-stylix.nix, etc.
 The files also look identical accross devices
 I am not using nixvim
 
 For now i have disabled the nvim module, but i would prefer for it to work like my other machine
 
 Does anyone know what could be going on here?

**Comment by WJehee** [comment]
I'm not sure what the issue was, but seems it solved itself.
I can't reproduce it anymore, so I'm closing this issue

**Comment by TheSaintDiratof** [comment]
I had same issue. I think it happes because some shell. I use tcsh and had same issue, but after rehash this issue disappears.
