### ISSUE TITLE
missing styling for bspwm

### ISSUE THREAD

**Issue by realsnick** [danth/stylix#39]

**Comment by dwarfmaster** [comment]
I feel like there is no obvious way to map base16 colors to bspwm configuration. What kind of mapping to you have in mind ?

After a quick search, I found the following theme [base16-builder](https://github.com/base16-builder/base16-builder/tree/master/db/templates/bspwm)

**Comment by realsnick** [comment]
that can be a very good start... Stylix is opinionated so its fine

**Comment by realsnick** [comment]
if you can show me a base line of it i can help with adjustments ...just too busy right now with other stuff

**Comment by dwarfmaster** [comment]
I opened #44 to discuss about the styling decisions.

**Comment by realsnick** [comment]
aweomse
