### ISSUE TITLE
treewide: GitHub Action failures

### ISSUE THREAD

**Issue by trueNAHO** [danth/stylix#403]
Recently, some (often only the last one) of the testbed GitHub Actions fail, and I manually re-run them to success. Ideally, this should be resolved.

Usually they fail due to timeout or somehow losing internet connection or not being able to download something.

I know GitHub Actions have an expected low probability failure rate. But now it happens nearly all the time.

Here is one example: https://github.com/danth/stylix/actions/runs/9268432783/attempts/1.

**Comment by danth** [comment]
Could this be related to the Magic Nix Cache action?

**Comment by trueNAHO** [comment]
Closing this issue, as it seems like the GitHub Actions are no longer timing out.
