### ISSUE TITLE
Release 24.05

### ISSUE THREAD

**Issue by Lord-Valen** [danth/stylix#416]
NixOS 23.11 is deprecated. Can we expect a branch-off targeting NixOS 24.05?

**Comment by trueNAHO** [comment]
Related: https://github.com/danth/stylix/issues/405

**Comment by danth** [comment]
Is there anything on `master` which needs to be rolled back? If not I can simply create the branch now.

**Comment by arunoruto** [comment]
> Is there anything on `master` which needs to be rolled back? If not I can simply create the branch now.

I am currently using the `master` branch and it works fine for now. Is it possible to roll back the branch afterward, in case some problems do come up?

**Comment by trueNAHO** [comment]
> > Is there anything on `master` which needs to be rolled back? If not I can simply create the branch now.
>
> I am currently using the `master` branch and it works fine for now.

Sounds good to me then. @danth, feel free to open the branch.

> Is it possible to roll back the branch afterward, in case some problems do come up?

Yes, we try to backport those things. For reference, here is what has been backported to the `release-23.11` branch: https://github.com/danth/stylix/compare/master...release-23.11

**Comment by danth** [comment]
Eventually, we could start backporting all non-breaking changes to the branch too.

**Comment by danth** [comment]
I created the `release-24.05` branch.
