### ISSUE TITLE
dimming background image

### ISSUE THREAD

**Issue by realsnick** [danth/stylix#45]
Sometimes I have background images that are bright, will be nice to be able to have the ability to dimm the image. 

```nix
stylix = {
   polarity = "dark";
   image "..."
   image-dimming = "0.3";
}
```

**Comment by danth** [comment]
You could pass the file through ImageMagick before setting it as the background:

```nix
{ pkgs, ... }:

{
  stylix.image = pkgs.runCommand "image.jpg" {} ''
    ${pkgs.imagemagick}/bin/magick ${./image.jpg} -level 0%,100%,0.5 $out
  '';
}
```

**Comment by realsnick** [comment]
Perfect! Will check it out

**Comment by dwarfmaster** [comment]
I think starting to add wallpaper transformations should be considered outside of the scope of the project, since they are easily worked around. However we could have a `TRICKS.md` with a list of examples of how to do this kind of things.
