### ISSUE TITLE
Question about Window-Bar-Styling

### ISSUE THREAD

**Issue by OriginalJohann** [danth/stylix#450]
Hello everyone.

I would like to know, if it is correct, that my Window-bars receive an odd styling while the base16-lime-theme is selected (see picture). I expected the top bar to use the greenich-coloring of the entire theme. 

I could switch to darkmode, getting a darker color, but 1. this does not match the dark blue of the background and 2. darkmode breaks thunderbird's styling. 

![Bildschirmfoto vom 2024-06-24 10-07-16](https://github.com/danth/stylix/assets/13522327/5f7ea267-7a0d-438c-9bc9-620bf6f32d20)

**Comment by danth** [comment]
What's the name of the terminal app, and which window manager are you using?

**Comment by OriginalJohann** [comment]
Oh, this is the gnome terminal and I am  running on Gnome46. I thought the image would tell everyone that much :) This coloring also happens if I am not using the extraArgs (removing rounded corners).

**Comment by OriginalJohann** [comment]
Oh, this is the gnome terminal and I am running on Gnome46. I thought the image would tell everyone that much :) This coloring also happens if I am not using the extraArgs (removing rounded corners).

**Comment by trueNAHO** [comment]
In the future, https://github.com/danth/stylix/issues/249 should resolve these type of issues.

**Comment by danth** [comment]
> I thought the image would tell everyone that much :)

Silly me, I was only paying attention to the window bars...

I'm assuming GNOME Terminal uses GTK. In that case, it *should* be themed without requiring a Stylix module of its own. Are any other GTK apps showing the colors you set in Stylix?

**Comment by OriginalJohann** [comment]
> > I thought the image would tell everyone that much :)
> 
> Silly me, I was only paying attention to the window bars...
> 
> I'm assuming GNOME Terminal uses GTK. In that case, it *should* be themed without requiring a Stylix module of its own. Are any other GTK apps showing the colors you set in Stylix?

Nope. All of them show the "wrong" header bar. The terminal itself has the right colors. Only the headerbar is wrong. Or I think, it is wrong. I was hoping, that someone could test this with the lime-theme and a gtk app.

**Comment by danth** [comment]
In that case, this seems like an issue with your GTK theme applying in general.

Potentially related: #443

**Comment by OriginalJohann** [comment]
> In that case, this seems like an issue with your GTK theme applying in general.

So it is an issue. Thank you very much, I can live with that :D I was afraid, that I did something wrong.

**Comment by trueNAHO** [comment]
Should this issue be superceded (closed) by https://github.com/danth/stylix/issues/249 and https://github.com/danth/stylix/discussions/443?

**Comment by OriginalJohann** [comment]
> Should this issue be superceded and closed by #249 and #443?

Yeah. I think this is the right approach
