### ISSUE TITLE
Add support for styling waybar

### ISSUE THREAD

**Issue by DamienCassou** [danth/stylix#46]
[Waybar](https://github.com/Alexays/Waybar/) seems to be a popular choice for [sway](https://swaywm.org/) users.

**Comment by dwarfmaster** [comment]
Some relevant link:
- https://aflab.fr/blog/my-custom-tilling-windows-manager-with-a-uniform-look/#waybar
- https://github.com/mnussbaum/base16-waybar
- https://github.com/Alexays/Waybar/wiki/Styling#minimal-style

**Comment by Henry-Hiles** [comment]
Doesnt this exist? https://github.com/danth/stylix/tree/master/modules/waybar

**Comment by DamienCassou** [comment]
You are right, closing.
