### ISSUE TITLE
[Feature Request] Recolor wallpaper when possible

### ISSUE THREAD

**Issue by Mikilio** [danth/stylix#469]
Right now when supplying a wallpaper the colorscheme gets generated by a genetic algorithm. When a colorscheme is also supplied it is chosen instead. I would like to add the possibility to recolor the wallpaper using a tool like [PaletteNet](https://github.com/AakritiKinra/PaletteNet-Implementation) when both are supplied. This option to enable this should be opt-out.

I wanted to work on this for myself. When it's done I would need some help integrating it into stylix because it's quite a big repo and I don't know where to change stuff.

**Comment by trueNAHO** [comment]
Potentially related:

> > The `options.stylix.targets.<TARGET>.wallpaper` options would be `<TARGET>` specific, similar to `options.stylix.targets.<TARGET>.enable`.
> >
> > Based on the following use cases, it makes sense to add a `stylix.enableWallpaper` option complementary to `stylix.autoEnable`:
> >
> > * Get color scheme from `stylix.image` without setting `stylix.image` as wallpaper: `stylix = { enableWallpaper = false; image = image; }`.
> > * Get color scheme from `stylix.image` and set `stylix.image` as wallpaper: `stylix = { enableWallpaper = true; image = image; }`.
> > * Manually declare color scheme (`stylix.base16Scheme`) and entirely ignore `stylix.image`: `stylix = { base16Scheme = base16Scheme; enableWallpaper = false; image = null; }`.
> >
> > For reference, [it has been considered to better rename the `stylix.autoEnable` option](https://github.com/danth/stylix/pull/244#issuecomment-2156716903). Additionally, these use cases somewhat correspond to the [slideshow feature suggestion](https://github.com/danth/stylix/issues/63).
>
> -- https://github.com/danth/stylix/issues/442#issuecomment-2185005008

**Comment by LovingMelody** [comment]
This previously was possible to be done by the user [as notated in Tips & tricks](https://stylix.danth.me/tricks.html#dynamic-wallpaper-generation-based-on-selected-theme) however as I've reported in #437 this is no longer working. This would likely close that issue in the process

**Comment by Mikilio** [comment]
This is not quite what I was referring to. I hoped to have a supported default smart recoloring mechanism. And I from what I was able to try, PaletteNet offered the best results. (Definitely better than lutgen).

**Comment by LovingMelody** [comment]
Example code in the issue just happens to be what I use, there's no real reason why it couldn't be substituted for pretty much anything else. The issue occurred from the color palette being referenced but for some reason stylix is still attempting to reference one generated from the image.

**Comment by Mikilio** [comment]
>Example code in the issue just happens to be what I use, there's no real reason why it couldn't be substituted for pretty much anything else. The issue occurred from the color palette being referenced but for some reason stylix is still attempting to reference one generated from the image.

To be honest, I'm a bit confused what you mean because all is working well on my side regarding this.

I actually already have a configuration that works for this locally. I'm just not happy with the result yet.
That is why I was thinking that retraining the model for base16/base24 colors would be nice. (reading the paper, there is no reason why this would not work)

**Comment by Mikilio** [comment]
#473 seems like a good general design for the feature I'm looking for. As such, I will close this issue and defer to that. Should I ever make progress on my front, I'll mention it there.
