### ISSUE TITLE
neovim: extract from VIM module

### ISSUE THREAD

**Issue by trueNAHO** [danth/stylix#471]
The `stylix.targets.vim.enable` option guards

https://github.com/danth/stylix/blob/29148118cc33f08b71058e1cda7ca017f5300b51/modules/vim/hm.nix#L57-L58

For consistancy, we should add a `stylix.targets.neovim.enable` option and declare it in a new `modules/neovim/hm.nix` module.

Whether `stylix.targets.neovim.enable` and `stylix.targets.vim.enable` should be aliases is still an open question.

**Comment by danth** [comment]
IMO they should be separate toggles, but share the same code as they do now - either by importing from a common location or just defining both targets in the same file.

**Comment by donovanglover** [comment]
FWIW I've been using [base16-nvim](https://github.com/RRethy/base16-nvim) since it produces better colors (especially with nvim-lspconfig).

Wouldn't mind [making a PR](https://github.com/donovanglover/stylix/commit/f76b04561ae6a1bdf3fe851df0d0233809aab88f) if this is something wanted.

**Comment by trueNAHO** [comment]
> FWIW I've been using [base16-nvim](https://github.com/RRethy/base16-nvim) since it produces better colors (especially with nvim-lspconfig).
> 
> Wouldn't mind [making a PR](https://github.com/donovanglover/stylix/commit/f76b04561ae6a1bdf3fe851df0d0233809aab88f) if this is something wanted.

LGTM
