### ISSUE TITLE
kde: kwallet is unexpectedly installed

### ISSUE THREAD

**Issue by danth** [danth/stylix#479]
After commit 6bbae4f85b891df2e6e48b649919420434088507, kwallet is now installed on my system and has taken over as the default keyring.

I tried experimenting with the list of packages, and it seems that `plasma-integration` depends on it. I'm not sure how we can avoid installing kwallet without removing that package, since the theming breaks without it.

There may also be a setting to disable it at runtime which I'm not aware of.

CC @Jackaed

**Comment by Jackaed** [comment]
Are you certain this is plasma-integration? My initial suspect for this would be kdePackages.full, and libsForQt5.full. If it's plasma-integration then I'm not sure what we can do.

**Comment by Jackaed** [comment]
Doing some testing on my own system, I think what's causing this is `kdePackages.full`. The reason I had this installed in the first place was to allow for icons to show up on qt6, when they weren't without kdePackages. I have no clue why this is happening, but it might be that there's a specific smaller package I can install that does the same job.

**Comment by Jackaed** [comment]
Kwallet seems to be installed when I do so much as install dolphin. Not sure what can be done about this.

**Comment by danth** [comment]
From my testing it seemed like I had to remove both `full` and `plasma-integration` to get rid of the dependency.

As for why it's become the default - I don't think I have any other keyrings installed at the moment. It appears when opening Brave browser, prompting me to enter my password, although I assume other applications which need a keyring would also use it.

**Comment by trueNAHO** [comment]
Closing this issue in favor of #489:

> IMHO, issues related to #490 should be closed to distinguish existing and non-existing problems. However, the issues closed by #490 will serve as references and considerations for #489.
>
> -- https://github.com/danth/stylix/issues/487#issuecomment-2251366370
