### ISSUE TITLE
QT_QPA_PLATFORMTHEME has conflicting definition values

### ISSUE THREAD

**Issue by CUexter** [danth/stylix#480]
commit hash where this happens: 6f36b27
I think the problem happened in commit 6bbae4f
```
       error: The option `home-manager.users.username.home.sessionVariables.QT_QPA_PLATFORMTHE
ME' has conflicting definition values:
       - In `/nix/store/46j03wimy2jl40vgvdb74yip2aw5vq6p-modules/kde/hm.nix': "kde"
       - In `/nix/store/lk3d5lnbsxyv8bkr9vyqc589ivcgnz9n-source/modules/misc/qt.nix': "gtk2"
       Use `lib.mkForce value` or `lib.mkDefault value` to change the priority on any of these de
finitions.
```
I just run `nix flake update` and this happens

**Comment by Jackaed** [comment]
Make sure you're not setting `qt.style.name` anywhere in your config.

**Comment by CUexter** [comment]
how do i keep using my own theme ?

**Comment by Jackaed** [comment]
What do you mean? If you want to stop stylix from theming kde, then use `stylix.targets.kde.enable = false`.

**Comment by CUexter** [comment]
oh thanks I didn't realise it because I am not using kde

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by danth** [comment]
@Jackaed it might be a good idea to rename the target to Qt since it works everywhere now

**Comment by mrcjkb** [comment]
> If you want to stop stylix from theming kde, then use stylix.targets.kde.enable = false.

:thinking: I'm getting `error: The option `stylix.targets.kde' does not exist.` 

```
        "repo": "stylix",
        "rev": "0ef70039a6435446472182c8f8106947abfc523d",
```

**Comment by danth** [comment]
@mrcjkb The option is under Home Manager, not NixOS

**Comment by Jackaed** [comment]
> @Jackaed it might be a good idea to rename the target to Qt since it works everywhere now

Yeah this is probably a good idea.

**Comment by dwilliam62** [comment]
Question:  If you disable stylix for KDE won't that also disable stylix for any QT app?   Not only when using KDE?  I am using hyprland not KDE.  I want to fully understand the ramification of setting this:  stylix.targets.kde.enable = false.   which I have done to get rebuilds to complete.    Thank you

**Comment by Jackaed** [comment]
> Question: If you disable stylix for KDE won't that also disable stylix for any QT app? Not only when using KDE? I am using hyprland not KDE. I want to fully understand the ramification of setting this: stylix.targets.kde.enable = false. 

Correct, the KDE target is just Qt theming.

> which I have done to get rebuilds to complete. Thank you

Enable it and remove whatever part of your config is conflicting with Stylix and then it should work fine.

**Comment by danth** [comment]
> KDE target is just Qt theming

It also themes some parts of the KDE desktop such as the taskbar

**Comment by dwilliam62** [comment]
> > Question: If you disable stylix for KDE won't that also disable stylix for any QT app? Not only when using KDE? I am using hyprland not KDE. I want to fully understand the ramification of setting this: stylix.targets.kde.enable = false.
> 
> Correct, the KDE target is just Qt theming.
> 
> > which I have done to get rebuilds to complete. Thank you
> 
> Enable it and remove whatever part of your config is conflicting with Stylix and then it should work fine.

 Thank you for replying.   Is there gong to be any future changes to address this ?

**Comment by danth** [comment]
We should be using the `qt.platformTheme` option rather than setting environment variables directly

**Comment by Jackaed** [comment]
> We should be using the `qt.platformTheme` option rather than setting environment variables directly

I can't quite remember why I changed from doing this to setting environment variables directly - I think it's because I had issues trying to get using qt.platformTheme to work with Qt6. Not at my computer for the next few days so I can't go and have a look.

**Comment by danth** [comment]
I'm very busy at the moment but I'll look into it if I get a chance. Reading the source code for the Qt Home Manager module might explain what's going on

**Comment by Jackaed** [comment]
Ok looking through I can remember why I did it - it was causing a conflict when I did all of the qt6 stuff. Will fix on my branch - can make a PR but if we're reverting the original commit then there's not much point.
