### ISSUE TITLE
Compatibility issue with Plasma-manager

### ISSUE THREAD

**Issue by urioTV** [danth/stylix#485]
After update(not sure if it's an plasma-manager or stylix update) those two config-managers have a conflict on .config/kdeglobals. It completely breaks my config so I want to figure out where is the problem. I'll probably create the same issue on Stylix and Plasma-manager github.

**Comment by urioTV** [comment]
Flake.lock without this problem. That's the last update when everything were working.
```

"stylix": {
      "inputs": {
        "base16": "base16",
        "base16-fish": "base16-fish",
        "base16-foot": "base16-foot",
        "base16-helix": "base16-helix",
        "base16-kitty": "base16-kitty",
        "base16-tmux": "base16-tmux",
        "base16-vim": "base16-vim",
        "flake-compat": "flake-compat_2",
        "gnome-shell": "gnome-shell",
        "home-manager": "home-manager_3",
        "nixpkgs": "nixpkgs_4"
      },
      "locked": {
        "lastModified": 1720818679,
        "narHash": "sha256-u9PqY7O6TN42SLeb0e6mnYAgQOoQmclaVSHfLKMpmu0=",
        "owner": "danth",
        "repo": "stylix",
        "rev": "29148118cc33f08b71058e1cda7ca017f5300b51",
        "type": "github"
      },
      "original": {
        "owner": "danth",
        "repo": "stylix",
        "type": "github"
      }
    }

"plasma-manager": {
      "inputs": {
        "home-manager": [
          "home-manager"
        ],
        "nixpkgs": [
          "nixpkgs"
        ]
      },
      "locked": {
        "lastModified": 1720992717,
        "narHash": "sha256-8j1bZVfKT1vJ0e+U7NYRNBG+DdBj5C/tpwe5krxT4/4=",
        "owner": "pjones",
        "repo": "plasma-manager",
        "rev": "460b48dc3dcd05df568e27cbb90581d23baec8dc",
        "type": "github"
      },
      "original": {
        "owner": "pjones",
        "repo": "plasma-manager",
        "type": "github"
      }
    }



```

**Comment by urioTV** [comment]
Okay after some testing I'm pretty sure the problem is on Stylix part. Something must have change from rev 29148118cc33f08b71058e1cda7ca017f5300b51 and now Stylix writes something to .config/kdeglobals.

**Comment by urioTV** [comment]
Someone from plasma-manager said that it started from 6bbae4f85b891df2e6e48b649919420434088507 commit. Is there any way to make it compatible with plasma-manager or is there a way to disable this specific functionality?

**Comment by trueNAHO** [comment]
> Someone from plasma-manager said that it started from 6bbae4f85b891df2e6e48b649919420434088507 commit.

Yes, unfortunately this commit has been repeatedly reported to cause problems:

- #480
- #487

> Is there any way to make it compatible with plasma-manager or is there a way to disable this specific functionality?

Ensuring compatibility requires fixing 6bbae4f85b891df2e6e48b649919420434088507. Currently, to disable this patch you would sadly have to downgrade Stylix prior to 6bbae4f85b891df2e6e48b649919420434088507.

@Jackaed, @danth, should we revert 6bbae4f85b891df2e6e48b649919420434088507 for now, as it is causing loads of problems?

**Comment by Jackaed** [comment]
> @Jackaed, @danth, should we revert 6bbae4f for now, as it is causing loads of problems?

That seems like it might be sensible - I think we probably should try and talk to some people from KDE itself if possible to figure out what the "correct" way of trying to achieve our goals. My PR was a bit too based on "well it works for me" I think, there's probably a better way of going about things that I'm just not aware of.

**Comment by Jackaed** [comment]
I'm going to have a look at how `plasma-manager` does things with regards to the kdeglobals file - might be able to find a better way of doing things.

**Comment by danth** [comment]
Yes, I would agree with reverting for now. Having this commit in `master` for a while has at least helped to expose more issues which we hadn't even considered before, so we can develop a better solution before releasing again.

Also, while looking up the `qt.plaformTheme` option earlier, I noticed Home Manager has a set of `kconfig` options available which could be relevant, although their implementation looks like it's just calling a command for each individual option set.

Looking at `plasma-manager` seems like a good next step.

**Comment by HeitorAugustoLN** [comment]
> I'm going to have a look at how `plasma-manager` does things with regards to the kdeglobals file - might be able to find a better way of doing things.

What is probably causing the issue here is the kdeglobals file being read-only.
We use our own script to write configuration to files.
