### ISSUE TITLE
Zellij module has bad contrast

### ISSUE THREAD

**Issue by prescientmoon** [danth/stylix#486]
I am using the `gruvbox-light` theme and the zellij bar at the bottom is next to unreadable 
![image](https://github.com/user-attachments/assets/08b5f57c-7b85-4093-977f-3e0d5be06a54)

Here's the generated base16 json file:
```json
{
  "base00": "f2e5bc",
  "base01": "ebdbb2",
  "base02": "d5c4a1",
  "base03": "bdae93",
  "base04": "665c54",
  "base05": "504945",
  "base06": "3c3836",
  "base07": "282828",
  "base08": "9d0006",
  "base09": "af3a03",
  "base0A": "b57614",
  "base0B": "79740e",
  "base0C": "427b58",
  "base0D": "076678",
  "base0E": "8f3f71",
  "base0F": "d65d0e",
  "scheme": "Stylix",
  "author": "Stylix",
  "slug": "stylix"
}
```

**Comment by danth** [comment]
It looks like this is using a `base08`-`base0F` color on top of `base05`, which shouldn't be done

**Comment by trueNAHO** [comment]
Here is the relevant Stylix code:

https://github.com/danth/stylix/blob/c974c17cd089dcbfb16fbde028dd00bcc05e3f73/modules/zellij/hm.nix#L11-L21

**Comment by KamWithK** [comment]
> Here is the relevant Stylix code:
> 
> https://github.com/danth/stylix/blob/c974c17cd089dcbfb16fbde028dd00bcc05e3f73/modules/zellij/hm.nix#L11-L21

What's a better alternative?

**Comment by KamWithK** [comment]
> It looks like this is using a `base08`-`base0F` color on top of `base05`, which shouldn't be done

Yeah looks like the red color needs to change to something else, but which value should be used for it? `base03` looks somewhat better imo

**Comment by trueNAHO** [comment]
> What's a better alternative?

> > It looks like this is using a `base08`-`base0F` color on top of `base05`, which shouldn't be done
> 
> Yeah looks like the red color needs to change to something else, but which value should be used for it? `base01` or `base03` look somewhat better imo

Aside from the [Style Guide](https://stylix.danth.me/styling.html), there is [currently no more formal specification](https://github.com/danth/stylix/issues/249). Follow common sense, if the Style Guide is insuffient and consider sharing screenshots of the made changes.

**Comment by KamWithK** [comment]
> > What's a better alternative?
> 
> > > It looks like this is using a `base08`-`base0F` color on top of `base05`, which shouldn't be done
> > 
> > Yeah looks like the red color needs to change to something else, but which value should be used for it? `base01` or `base03` look somewhat better imo
> 
> Aside from the [Style Guide](https://stylix.danth.me/styling.html), there is [currently no more formal specification](https://github.com/danth/stylix/issues/249). Follow common sense, if the Style Guide is insuffient and consider sharing screenshots of the made changes.

Should text editor colors section apply? Its not a text editor but it is a terminal application

**Comment by trueNAHO** [comment]
> I'm just using base01 for mine that looks the best from trial and error so far

Feel free to submit a PR.

**Comment by KamWithK** [comment]
> > I'm just using base01 for mine that looks the best from trial and error so far
> 
> Feel free to submit a PR.

I am planning to create a PR for how the the Zellij theme gets set (currently it's with the main config but it really should be set via a theme file), I'll roll the change into that one :smile:
