### ISSUE TITLE
foot + tmux + fish = frozen shell

### ISSUE THREAD

**Issue by bonsairobo** [danth/stylix#488]
When I run `tmux` inside of `foot` terminal, I get just a white cursor in the top left corner of the terminal; the shell seems to never start accepting input. It doesn't go away until I do Ctrl+D to exit tmux.

When I switch my user's shell from `fish` to `bash`, the problem goes away.

When I use kitty instead of foot, the problem goes away.

**Comment by danth** [comment]
Does this work correctly without Stylix?

**Comment by bonsairobo** [comment]
@danth yes

**Comment by donovanglover** [comment]
Not sure if related but with tmux + fish and kitty it shows the white cursor instead of the prompt at startup but I can start typing after a few seconds.

**Comment by donovanglover** [comment]
FWIW the issue is caused by [base16-fish](https://github.com/danth/stylix/blob/master/modules/fish/prompt.nix) and was first reported 3 years ago. Upstream issue:

- https://github.com/tomyun/base16-fish/issues/7#issuecomment-963376055
