### ISSUE TITLE
VSCODE: add font size settings

### ISSUE THREAD

**Issue by no-mood** [danth/stylix#509]
Currently, the HM VS Code module sets the font but not its size. There are many options we can set, here is an example:

```nix
    "customPresentationMode.overrides": {
        "debug.console.fontSize": 26,
        "editor.fontSize": 26,
        "markdown.preview.fontSize": 26,
        "terminal.integrated.fontSize": 26,
    },
    "debug.console.fontSize": 16,
    "editor.fontSize": 16,
    "markdown.preview.fontSize": 16,
    "terminal.integrated.fontSize": 16,
```
We could set them according to the four types

**Comment by trueNAHO** [comment]
Feel free to open a PR.

**Comment by Flameopathic** [comment]
vscode seems to handle font sizes oddly, prolly something electron scaling related. tried this stuff in a fork, and everything was incredibly small

**Comment by danth** [comment]
Maybe it's measured in pixels rather than points?

**Comment by Flameopathic** [comment]
https://code.visualstudio.com/docs/getstarted/settings#_default-settings
```
// Controls the font size in pixels.
"editor.fontSize": 14,
```
you're exactly right, great call. 

is there a precedent for this? if i multiply by 4px/3pt, should i round or truncate? should it be specified in the book that font sizes are in pt?

**Comment by trueNAHO** [comment]
> searched codebase for all times font sizes are used, couldn't find anything that has had to do this before.

See https://github.com/danth/stylix/issues/251.

**Comment by Flameopathic** [comment]
> See https://github.com/danth/stylix/issues/251.
whoops. thank you

**Comment by Flameopathic** [comment]
will take inspiration from [this older conversion](https://github.com/trueNAHO/stylix/blob/197b81c6ccdc10148d09e6064861e3f20d5a26b9/modules/qutebrowser/hm.nix#L219C9-L219C78) for now then
