### ISSUE TITLE
Suggest: Add support for changing icon theme from stylix

### ISSUE THREAD

**Issue by Esteban528** [danth/stylix#511]
While stylix is sometimes used in environments that don't have a full desktop environment, so changing the icon theme I haven't been able to since stylix creates the gtk configuration file and defaults to adwaita, it would be ideal for stylix to take care of this.

**Comment by trueNAHO** [comment]
Is this issue a duplicate of https://github.com/danth/stylix/issues/458?

**Comment by danth** [comment]
> stylix creates the gtk configuration file and defaults to adwaita

The icon theme configured in that file can be changed directly in Home Manager using the `gtk.iconTheme` option.
