### ISSUE TITLE
New `fish` conditional prompt doesn't work properly

### ISSUE THREAD

**Issue by bddvlpr** [danth/stylix#538]
Since the last commit to the prompt two weeks ago, my fish theme isn't being applied anymore. Specifically, the `test -n "$base16_theme"` condition fails (exit code 1) and thus doesn't apply my theme.

![image](https://github.com/user-attachments/assets/d79a2050-5a62-46df-a1ec-e8d2ad06f175)

**Comment by trueNAHO** [comment]
Cc: @donovanglover

> Since the last commit to the prompt two weeks ago, my fish theme isn't being applied anymore.

The commit in question is 94d70292d0c6 ("fish: fix base16-fish causing startup issues with tmux (#503)").

> Specifically, the `test -n "$base16_theme"` condition fails (exit code 1) and thus doesn't apply my theme.

Do you know why `$base16_theme` is not set?

**Comment by bddvlpr** [comment]
I don't see why it should be set in the first place. Shouldn't stylix handle that? Before said configuration no additional settings had to be applied to fish.

**Comment by donovanglover** [comment]
Oversight on my part. Thanks for catching this.
