### ISSUE TITLE
animations as backgrounds

### ISSUE THREAD

**Issue by SomeGuyNamedMy** [danth/stylix#54]
i cant quite get to it yet due to mid terms for the next few weeks, but i wanna open an issue to get opinions on implementation.

**Comment by dwarfmaster** [comment]
I'm not sure how we should go about that. I was thinking of refactoring the wallpaper module, so maybe it could include facilities for using an animation as background (for example using mpv on x11), but `stylix.image` would still need to be set to a static picture. Maybe we could add an example in the FAQ of how to automatically set `stylix.image` to the first frame of an animation using `mpv` ?

**Comment by SomeGuyNamedMy** [comment]
im a fan of what you brought up before in the discussions tab, ie making a separate option, `stylix.animation` and generating `stylix.image' from that and using it as a fallback.
