### ISSUE TITLE
Chromium/Brave don't follow system colour after disabling Stylix

### ISSUE THREAD

**Issue by mvolf** [danth/stylix#546]
I used Stylix to set up the styling of my system. I decided do disable it for the time being and after doing so Chroimuim and Brave no longer follow system colours when using GTK as theme. Not only this, but these browsers stay light even if I manually set colours to "Dark".
This worked as expected prior to me using Stylix. Any thoughts or suggestions?

**Comment by mvolf** [comment]
Fixed after installing adw-gtk3. This is still weird since I never had this installed previously...

**Comment by danth** [comment]
Stylix themes these browsers using `/etc/chromium/policies/managed/extra.json` and `/etc/brave/policies/managed/extra.json` respectively
