### ISSUE TITLE
Feature Request: `lib.mkDefault` by default

### ISSUE THREAD

**Issue by uimataso** [danth/stylix#549]
Hi, I have used stylix quite some time, absolute loving this project.

But recently I notice a little inconvenience. For example, if I enabled stylix config for `tofi`, and I want to overwrite some config, I can't just `font-size = 20;`, I need to `font-size = lib.mkForce 20`. This means I need to manually check what config are already config in stylix, and worst part to me is some config need `lib.mkForce` and some not, so this brings some inconsistency.

So my wish is to make all config in stylix with `lib.mkDefault`, which is more sense and more intuitive to me.

But that been said, I don't know if `lib.mkDefault` will make sense in more complicated module tho.

And again, this is a wonderful project, thanks to all your hard work!

**Comment by trueNAHO** [comment]
This has already been proposed and discussed in https://github.com/danth/stylix/pull/388#issuecomment-2126947630.

**Comment by uimataso** [comment]
Ohhh, I have search `mkDefault`, but somehow didn't see it :(, I will close the this issue
