### ISSUE TITLE
`stylix.targets.<any>` does not exist.

### ISSUE THREAD

**Issue by daniel-hernandez-sony** [danth/stylix#554]
I am trying to setup `stylix` on my system. But I cannot figure out why things break when any of the `stylix.targets.<any>.enable` is accessed. I have been messing around for a while but I am completely at a loss. Whenever I set the `enable` option in any `stylix.targets` I get a `error: The option 'stylix.targets.<something>' does not exist.`

Does something basic scream out at you from my small config?

**Setup:**

Relevant parts from `flake.nix`:

```nix
{
  inputs = {
    # Nixpkgs
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";

    stylix = {
      url = "github:danth/stylix";
      inputs = {
        nixpkgs.follows = "nixpkgs";
        home-manager.follows = "home-manager";
      };
    };
    home-manager.url = "github:nix-community/home-manager/";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = { nixpkgs, home-manager, ... }@inputs:
    {
      # NixOS configuration entrypoint
      # Available through 'nixos-rebuild --flake .#your-hostname'
      nixosConfigurations = {
        fell-omen = nixpkgs.lib.nixosSystem {
          system = "x86_64-linux";
          modules = [
            inputs.stylix.nixosModules.stylix
            home-manager.nixosModules.default # Otherwise home-manager isn't imported
          ];
        };
      };
    };
}
```

And then within my `configuration.nix`:

```nix
  stylix = {
    enable = true;
    targets.neovim.enable = false;
    image = <path-to-jpg>;
 };
```

```
warning: Git tree '/home/daniel/nix_config' is dirty
error:
       … while calling the 'seq' builtin

         at /nix/store/2pw5bsq1r80lcvvh2wp89m142nln1zpl-source/lib/modules.nix:334:18:

          333|         options = checked options;
          334|         config = checked (removeAttrs config [ "_module" ]);
             |                  ^
          335|         _module = checked (config._module);

       … while calling the 'throw' builtin

         at /nix/store/2pw5bsq1r80lcvvh2wp89m142nln1zpl-source/lib/modules.nix:310:18:

          309|                     ''
          310|             else throw baseMsg
             |                  ^
          311|         else null;

       error: The option `stylix.targets.neovim' does not exist. Definition values:
       - In `/nix/store/jgsh6nwv9sjcjjbd6i31k39wygh02z19-source/non_home_manager_config/stylix.nix':
           {
             enable = false;
           }
```

**Comment by PsyNyde** [comment]
`stylix.target.neovim` isn't part of nixos option. it's only available inside home-manager.
even if you enable this in home-manager you'll need to enable neovim for example through `programs.neovim.enable` which is again part of home-manager option.
check [this](https://stylix.danth.me/options/nixos.html) page if you don't know which targets are available on nixos and which are on home-manager.

**Comment by daniel-hernandez-sony** [comment]
Pardon my ignorance, reading from the docs:

_When Stylix is installed to a NixOS configuration, it will automatically set up its Home Manager modules if it detects that Home Manager is available._

From this I thought that I would be able to access the home-manager modules. Do you know how I can access the home-manager modules this way?

**Comment by trueNAHO** [comment]
Cc: @danth

**Comment by PsyNyde** [comment]
> From this I thought that I would be able to access the home-manager modules. Do you know how I can access the home-manager modules this way?

sorry for my late reply. you probably have 
```nix
home-manager.nixModules.home-manager{
 user.yourusername = import ./path/to/home.nix;
}
```
something like this. you need to add your stylix home manager module in that file.

**Comment by danth** [comment]
When using NixOS and Home Manager together you need to access Home Manager targets as follows:

```nix
home-manager.users.«username».stylix.targets.neovim.enable = false;
```

Or for all users rather than a specific username:

```nix
home-manager.sharedModules = [{
  stylix.targets.neovim.enable = false;
}];
```

**Comment by daniel-hernandez-sony** [comment]
This did indeed fix the issue. Thank you everyone!
