### ISSUE TITLE
theme: background image

### ISSUE THREAD

**Issue by Zickles** [danth/stylix#558]
Is there a way to disable the background theme so it is not required??

I am trying to use another program for background but i have some other stuff like overrides that style other things that i want so i cant just stop using stylix.

im using flakes on unstable

**Comment by trueNAHO** [comment]
> Is there a way to disable the background theme so it is not required??

If "background theme" referrs to the background image (`stylix.image`), then this is a duplicate issue of: https://github.com/danth/stylix/issues/442.

**Comment by Zickles** [comment]
yeah that is what i meant

**Comment by trueNAHO** [comment]
Closing this as duplicate issue.
