### ISSUE TITLE
Infinite recursion encountered

### ISSUE THREAD

**Issue by kay-mw** [danth/stylix#561]
I recently updated my flake inputs and encountered an infinite recursion error when attempting to rebuild my system. After some troubleshooting, I found that removing the NixOS stylix module from my config fixed the error. My home manager stylix config seems to be fine.

 I am not sure what is responsible, but I have tried the following troubleshooting steps:

- Reverting to/trying various older stylix commits (including the commit my flake was previously on).
- Trying a basic version of my stylix config, with just the required options.
- Commenting out specific parts of my config to see if any specific option was responsible.
- Switching to different branches of nixpkgs (unstable/master/23.05).
- Commenting out other parts of my overall NixOS config to see if some conflict was responsible (I didn't do this step _super_ comprehensively, however).
- Misc. things like trying out a different wallpaper image and switching to a different base16 colorscheme

None of these steps were successful. Below is my NixOS stylix config and the full trace.

<details>
<summary>/modules/nix/stylix/default.nix</summary>
<br>

```
{ pkgs, ... }:

{
  stylix = {
    enable = true;
    autoEnable = false;
    image = ./equivalent_exchange.jpeg;
    polarity = "dark";
    imageScalingMode = "fit";
    base16Scheme = "${pkgs.base16-schemes}/share/themes/kanagawa.yaml";
    homeManagerIntegration.followSystem = true;

    fonts = {
      sizes = {
        applications = 9;
        terminal = 11;
      };
      monospace = {
        package = pkgs.meslo-lgs-nf;
        name = "MesloLGS NF Regular";
      };
    };

    cursor = {
      name = "Bibata-Modern-Classic";
      package = pkgs.bibata-cursors;
      size = 20;
    };

    targets = {
      chromium.enable = true;
      gnome.enable = true;
      gtk.enable = true;
    };
  };
}
```
</details>

Trace: https://gist.github.com/kay-mw/acc5e6751abf18b6cc3eff5e1385bd4b

**Comment by trueNAHO** [comment]
```nix
    autoEnable = false;
```

Try setting `autoEnable` to its default value (`true`).

Maybe this is related to https://github.com/danth/stylix/pull/419.

**Comment by kay-mw** [comment]
> > ```nix
> >     autoEnable = false;
> > ```
> 
> Try setting `autoEnable` to its default value (`true`).
> 
> Maybe this is related to #419.

Just gave that a go, unfortunately I am still getting the same infinite recursion error.

**Comment by heyimnova** [comment]
I ran into that same infinite recursion error. I found that holding nixvim back on an older version prevents it. Are you using also nixvim and could it be conflicting here?

**Comment by kay-mw** [comment]
> I ran into that same infinite recursion error. I found that holding nixvim back on an older version prevents it. Are you using also nixvim and could it be conflicting here?

Thank you! I do use nixvim, and indeed reverting to a previous commit fixed the infinite recursion issue. Specifically, it seems that  [this specific commit](https://github.com/nix-community/nixvim/commit/4e5bd1d79bb88b98e4d23241096989373150112c#diff-84f980eccc1d3f99c10f8b0e6c5c5fc2af2069517533c4c4d73264a190e85188) is where the error begins, which makes sense as it does mention infinite recursion as a potential problem across the commit description and code comments.

My nix proficiency is far too low to understand _why_ this commit leads to an infinite recursion, specifically when you have a stylix NixOS configuration enabled (I tried forking nixvim to figure it out, but didn't really get anywhere). I'll close this issue for now, as it seems like it's more of a nixvim issue and not a stylix issue, but I very well may be wrong so feel free to re-open it if that's the case!

**Comment by cgahr** [comment]
> > autoEnable = false;
> 
> Try setting `autoEnable` to its default value (`true`).
> 
> Maybe this is related to [#419](https://github.com/danth/stylix/pull/419).

Had a similar issue, and this solved it for me. Thanks a lot!
