### ISSUE TITLE
bug: inconsistant color between terminals (foot & kitty)

### ISSUE THREAD

**Issue by psynyde** [danth/stylix#567]
![image](https://github.com/user-attachments/assets/f9355a89-ce36-4645-9150-01700f2577f5)

As seen in the preview same colorscheme generating different terminal colors for foot (left) and kitty(right) (foot has the correct coloring). also kitty's [wiki](https://sw.kovidgoyal.net/kitty/conf/#the-color-table) also suggests the same thing.
this is the color pallet i'm using to generate colors:
```nix
    lackluster = {
      scheme = "Lackluster dark";
      author = "PsyNyde/Slugbyte(oc)";
      base00 = "#101010"; # background
      base01 = "#080808"; # (Black)
      base02 = "#191919"; # (Bright Black)
      base03 = "#2a2a2a"; # (gray)
      base04 = "#555555"; # (light gray)
      base05 = "#deeeed"; # foreground
      base06 = "#f0f0f0"; # (light foreground)
      base07 = "#ffffff"; # (lightest foreground)
      base08 = "#e64a6b"; # (Bright red)
      base09 = "#e69b7b"; # (Orange)
      base0A = "#f0c674"; # (Yellow)
      base0B = "#789978"; # (Green)
      base0C = "#6f8595"; # (Cyan)
      base0D = "#7788AA"; # (Blue)
      base0E = "#b86cd4"; # (magenta)
      base0F = "#e64a6b"; # (Dark red)
    };
```

**Comment by trueNAHO** [comment]
Related: https://github.com/danth/stylix/issues/249

**Comment by PsyNyde** [comment]
@danth @trueNAHO looks like the bug was caused by tinted-kitty template not matching specs and after tinted-theming/tinted-kitty#4 gets merged into main it should be fixed.

But also as the pr suggests 256 variants will be deprecated soon and will break `stylix.targets.kitty.variant256Colors` if I'm not being wrong. I'd love to see your input on this.

**Comment by trueNAHO** [comment]
> looks like the bug was caused by tinted-kitty template not matching specs. After [tinted-theming/tinted-kitty#4](https://github.com/tinted-theming/tinted-kitty/pull/4) is merged into main, it should be fixed. (edit. it has been merged)

Does https://github.com/danth/stylix/pull/588 resolve the issue?

> However, the pr also suggests 256 variants will be deprecated and removed soon, which will break `stylix.targets.kitty.variant256Colors` if I'm not being wrong.

Thanks for pointing this out. I suggest Stylix should deprecate the `stylix.targets.kitty.variant256Colors` option, following upstream decisions. Feel free to submit a PR.

**Comment by psynyde** [comment]
Hey @trueNAHO, sorry to bother you again, but after updating Stylix to the latest commit, it seems like I'm encountering the same issue as in #576. From my research, it looks like the problem stems from [this commit](https://github.com/tinted-theming/tinted-kitty/commit/9569d8a3e8dad5714174a015d955642641d295fb#diff-46d429f4b19179f06d6ff725d2dc2c8d24914503d59c4ab5fb27a0330b2c445f) in the tinted-kitty repository, where they updated the templates/config.yaml file. This seems to be the same issue that previously affected tinted-foot.

After checking the tinted repositories Stylix depends on (e.g. foot, kitty & tmux) ,it looks like updating any of their respective inputs will cause Stylix to break.

I can try to submit a pr to use local template instead of relying on external repo which will make it easier to maintain and update template when needed imo. but I'm not sure if this is the best way to handle this and I'm pretty new to nix so the pr can be a bit rough

**Comment by trueNAHO** [comment]
> after updating Stylix to the latest commit, it seems like I'm encountering the same issue as in #576. From my research, it looks like the problem stems from [this commit](https://github.com/tinted-theming/tinted-kitty/commit/9569d8a3e8dad5714174a015d955642641d295fb#diff-46d429f4b19179f06d6ff725d2dc2c8d24914503d59c4ab5fb27a0330b2c445f) in the tinted-kitty repository, where they updated the templates/config.yaml file. This seems to be the same issue that previously affected tinted-foot.
>
> After checking the tinted repositories Stylix depends on (i.e. foot, kitty & tmux) ,it looks like updating any of their respective inputs will cause Stylix to break.

Thanks for all the usefull input.

> I can try to submit a pr to use local template instead of relying on external repo which will make it easier to maintain and update template when needed imo. but I'm not sure if this is the best way to handle this and I'm pretty new to nix so the pr can be a bit rough

Considering that the [roadmap](https://github.com/danth/stylix/issues/534) eventually causes Stylix to implement all templates without relying on external dependencies, it might be easiest to lock the current dependency versions to avoid wasted maintenance effort.

> I am already looking into this. I will try to properly resolve this today.
>
> -- https://github.com/danth/stylix/issues/571#issuecomment-2403146875
