### ISSUE TITLE
"stylix.targets.wezterm.enable" does not exist

### ISSUE THREAD

**Issue by DrVoidest** [danth/stylix#569]
I think there may be an issue with the wezterm module. In my config I have `stylix.targets.wezterm.enable = false` and it the following error `error: The option "stylix.targets.wezterm" does not exist. Definition values:
┃        - In `/nix/store/xvl26ggs70i7kgpik34xbywrn2flsy0q-source/modules/stylix.nix':
{
┃              enable = false;
┃            }`
I checked the wiki and the spelling is correct as well as the wezterm module in stylix and it should be this option. I don't know if this is releated, but the reason I was trying to disable it was because wezterm was reporting the following issue `18:56:01.040  ERROR  mux::connui > Configuration Error: runtime error: [string "/home/neon/.config/wezterm/wezterm.lua"]:5: attempt to index a nil value (global 'config')
stack traceback:
	[string "/home/neon/.config/wezterm/wezterm.lua"]:5: in local 'stylix_wrapped_config'
	[string "/home/neon/.config/wezterm/wezterm.lua"]:10: in main chunk` line in question `-- Generated by Stylix
local wezterm = require("wezterm")
wezterm.add_to_config_reload_watch_list(wezterm.config_dir)
local function stylix_wrapped_config()
    config.front_end = "WebGpu"
config.enable_wayland = false

end
local stylix_base_config = wezterm.config_builder()
local stylix_user_config = stylix_wrapped_config()
stylix_base_config = {
    color_scheme = "stylix",
    font = wezterm.font_with_fallback {
        "FiraCode Nerd Font Propo",
        "Openmoji Color",
    },`

**Comment by trueNAHO** [comment]
AFAIK, the option should be available:

https://github.com/danth/stylix/blob/eccb9f2d63f4582b1c1ffe97d806156147aeee5f/modules/wezterm/hm.nix#L5-L6

How and where are you declaring this?

**Comment by DrVoidest** [comment]
I have it in /etc/nixos/modules/stylix.nix (Where I put all of my stylix stuff)

**Comment by danth** [comment]
WezTerm is configured in Home Manager, so you also need to set Stylix options for it there.

See https://github.com/danth/stylix/issues/554#issuecomment-2363421028 for an example if you're using Home Manager combined with NixOS.

**Comment by DrVoidest** [comment]
> WezTerm is configured in Home Manager, so you also need to set Stylix options for it there.
> 
> See [#554 (comment)](https://github.com/danth/stylix/issues/554#issuecomment-2363421028) for an example if you're using Home Manager combined with NixOS.

Thank you, this was what I was missing.
