### ISSUE TITLE
Hyprland

### ISSUE THREAD

**Issue by SomeGuyNamedMy** [danth/stylix#57]
Ive got a modules set up already based on the same coloring as the sway module, however im not sure weather up streaming would be a good idea considering that nixos and home-manager modules haven't been up streamed yet.

**Comment by dwarfmaster** [comment]
I think we could either:
- Add them in another directory as modules that are not imported by default.
- Decide we don't want to support modules that rely on features not upstreamed, in which case you could export them from another repo, and we could add a link in the FAQ.

**Comment by danth** [comment]
I don't think we should have modules on the main branch of Stylix that don't work with the main branch upstream.

You could either export the module from a separate repo as suggested, or add it to a fork of Stylix and keep that fork up to date by rebasing until it's suitable to be merged.

**Comment by SomeGuyNamedMy** [comment]
i,ll close the issue until the required hm module is up streamed

**Comment by danth** [comment]
Reopening this as the upstream module is now available
