### ISSUE TITLE
bug: rofi theme not generated for rofi-wayland

### ISSUE THREAD

**Issue by chakibchemso** [danth/stylix#581]
i have [rofi-wayland](https://search.nixos.org/packages?channel=24.05&show=rofi-wayland&from=0&size=50&sort=relevance&type=packages&query=rofi) installed instead of [rofi](https://search.nixos.org/packages?channel=24.05&show=rofi&from=0&size=50&sort=relevance&type=packages&query=rofi) cz im on hyprland. but the theme is not being generated even by forcing `stylix.targets.rofi.enable = true;`

**Comment by trueNAHO** [comment]
> i have [rofi-wayland](https://search.nixos.org/packages?channel=24.05&show=rofi-wayland&from=0&size=50&sort=relevance&type=packages&query=rofi) installed instead of [rofi](https://search.nixos.org/packages?channel=24.05&show=rofi&from=0&size=50&sort=relevance&type=packages&query=rofi) cz im on hyprland.

We are setting the theme with Home Manager's `programs.rofi.theme` option:

https://github.com/danth/stylix/blob/39e5435c1da9ce50fe36deaf58bd2b94dd4d8249/modules/rofi/hm.nix#L24-L26

Is this maybe a Home Manager limitation?

> the theme is not being generated even by forcing `stylix.targets.rofi.enable = true;`

This is the default value when setting `stylix.enable = true;`.

**Comment by chakibchemso** [comment]
maybe cz rofi is installed thru `environment.systemPackages` ?

**Comment by trueNAHO** [comment]
> maybe cz rofi is installed thru `environment.systemPackages` ?

Possible. Try setting it with `rofi.package`.

**Comment by chakibchemso** [comment]
yeah that did the trick:
```nix
  programs.rofi = {
    enable = true;
    package = pkgs.rofi-wayland;
  };
```
but honestly i dont like the theme, it changed the layout and spacing of the elements, like there's no padding at all? im sticking to the base16-catppuccin-mocha.rasi theme instead for now.
