### ISSUE TITLE
video content now following the color theme

### ISSUE THREAD

**Issue by dasj19** [danth/stylix#583]
Hello, I noticed that the video content in vlc and retroarch is following the current theme I chose. Which it should not.

My stylix configuration:

```
{ pkgs, ...}:
{
  stylix.enable = true;
  # Theme settings.
  stylix.base16Scheme = "${pkgs.base16-schemes}/share/themes/da-one-sea.yaml";
  stylix.image = "${pkgs.adapta-backgrounds}/share/backgrounds/adapta/tealized.jpg";
  stylix.polarity = "dark";
  stylix.opacity.applications = 1.0;
  stylix.opacity.desktop = 1.0;

  # Cursor settings.
  stylix.cursor.package = pkgs.bibata-cursors;
  stylix.cursor.name = "Bibata-Modern-Classic";
  # Font settings.
  stylix.fonts.serif.package = pkgs.ubuntu-classic;
  stylix.fonts.serif.name = "Ubuntu Classic";
  stylix.fonts.sansSerif.package = pkgs.fira-code-nerdfont;
  stylix.fonts.sansSerif.name = "UbuntuMono Nerd Font";
  stylix.fonts.monospace.package = pkgs.fira-code-nerdfont;
  stylix.fonts.monospace.name = "FiraCode Nerd Font";
}
```

![Screenshot from 2024-10-04 15-47-09](https://github.com/user-attachments/assets/8b1a2fc3-2250-477c-b364-53dbdb964f7f)
![Screenshot from 2024-10-04 19-33-11](https://github.com/user-attachments/assets/bc7ea09b-ef65-4d6c-83e8-12fd0fc9281c)

What do I need to do to get the colors back in VLC and other video software?

**Comment by dasj19** [comment]
Hmm... I updated my nixpkgs flake input and now everything is back to normal... I was on this branch before: https://github.com/Keksgesicht/nixpkgs/tree/master

**Comment by trueNAHO** [comment]
> Hmm... I updated my nixpkgs flake input and now everything is back to normal...

Should we close this issue?

**Comment by dasj19** [comment]
I'll close it, as I can not reproduce it with up-to-date flake inputs, If it occurs again I'll open a new one.
