### ISSUE TITLE
`programs.rofi.font` is not set correctly

### ISSUE THREAD

**Issue by qaristote** [danth/stylix#59]
I'm using Stylix and enabled Rofi inside Home Manager but it doesn't pick up the right font. Looking at the source, this seems to be because Stylix sets 
https://github.com/danth/stylix/blob/6d3a046d17675db57114dcfcd20e36eedb597967/modules/rofi/hm.nix#L20-L21
Whereas [this option actually expects the name of the font followed by the font size](https://nix-community.github.io/home-manager/options.html#opt-programs.rofi.font).
A possible fix would thus be to set
```nix
programs.font.rofi = "${monospace.name} 12"
```
but the font size should probably depend on some option.

**Comment by dwarfmaster** [comment]
Related issue #35 
As I said [there](https://github.com/danth/stylix/issues/35#issuecomment-1445201824), we need a way to handle font sizes. I haven't really had the time to think about it yet.
