### ISSUE TITLE
Error when trying to theme KDE

### ISSUE THREAD

**Issue by ShadowReaper420** [danth/stylix#595]
I the following error whenever I try to use the KDE module.

```

       error: getting status of '/nix/store/39c8m1rwg1arfmbc3pax1ml9hqc8hxk8-source/Modules/.dotfiles/Wallpapers/Kath.png': No such file or directory
┏━ 1 Errors:
┃ error:
┃        … while calling the 'head' builtin
┃
┃          at /nix/store/fpivx4sjcp2vk4rp9nhliln5cwcp3kc6-source/lib/attrsets.nix:1575:11:
┃
┃          1574|         || pred here (elemAt values 1) (head values) then
┃          1575|           head values
┃              |           ^
┃          1576|         else
┃
┃        … while evaluating the attribute 'value'
┃
┃          at /nix/store/fpivx4sjcp2vk4rp9nhliln5cwcp3kc6-source/lib/modules.nix:821:9:
┃
┃           820|     in warnDeprecation opt //
┃           821|       { value = addErrorContext "while evaluating the option `${showOption loc}':" value;
┃              |         ^
┃           822|         inherit (res.defsFinal') highestPrio;
┃
┃        (stack trace truncated; use '--show-trace' to show the full trace)
┃
┃        error: getting status of '/nix/store/39c8m1rwg1arfmbc3pax1ml9hqc8hxk8-source/Modules/.dotfiles/Wallpapers/Kath.png': No such file or directory
┣━━━
┗━ ∑ ⚠ Exited with 1 errors reported by nix at 04:41:55 after 11s
Error:
   0: Command exited with status Exited(1)
```

My stylix config.

```nix

{ config, pkgs, inputs, systemSettings, userSettings, ... }:
{
   stylix = {
      enable = true;
      image = ../.dotfiles/Wallpapers/Kath.png; # ignore this it wont actually be used for anything but the option is require for the time being
      base16Scheme = "${pkgs.base16-schemes}/share/themes/catppuccin-mocha.yaml";
      autoEnable = false;
      targets = {
        kitty.enable = true;
        lazygit.enable = true;
        gtk.enable = true;
        btop.enable = true;
        kde.enable = true;


     };
   };
}
```

**Comment by trueNAHO** [comment]
> I the following error whenever I try to use the KDE module.
>
> ```
> [...]
> ┃        error: getting status of '/nix/store/39c8m1rwg1arfmbc3pax1ml9hqc8hxk8-source/Modules/.dotfiles/Wallpapers/Kath.png': No such file or directory
> [...]
> ```
>
> My stylix config.
>
> ```nix
> [...]
>       image = ../.dotfiles/Wallpapers/Kath.png; # ignore this it wont actually be used for anything but the option is require for the time being
> [...]
> ```

Seems like your `stylix.image` value is in fact used and causing the problem.

**Comment by ShadowReaper420** [comment]
Okay? I can read the error the problem is it doesn't make sense considering that is a real wallpaper in my config, and it builds fine if I don't use the KDE module.

**Comment by danth** [comment]
@ShadowReaper420 can you check that:

- `Modules/.dotfiles/Wallpapers/Kath.png` exists within your config?
- It is added to Git using `git add`? (this is required for Nix to see the file)

When you have the KDE module disabled, there is nothing which needs to access the wallpaper, so the error about it not existing won't be triggered.

**Comment by ShadowReaper420** [comment]
I've given up and am just using something else to theme qt stuff until this is no longer hardcoded to need a wallpaper even when you don't use it

**Comment by IvanTurgenev** [comment]
same issue here
