### ISSUE TITLE
[BUG] targets.nixvim.enable = false does not do anything

### ISSUE THREAD

**Issue by knocking4thcylinder** [danth/stylix#600]
when setting `targets.nixvim.enable` to false stylix still overrides nixvim colorscheme with its own.

my confing can be found here: https://github.com/knocking4thcylinder/nix-config
related files are `stylix/default.nix` and  `home-manager/nixvim`. Also stylix is set up as NixOS module

**Comment by noahfraiture** [comment]
I think you can't define a target via nixos, it must be done via home-manager. However when I try that, stylix doesn't seem to detect the home-manager file because i have this error `The option 'stylix.image' was accessed but has no value defined. Try setting the option.`  Despite an image is well given. It might be the same problem for you

**Comment by noahfraiture** [comment]
> It says that you can in the manual, but adding `stylix.targets.nixvim.enable = false` in home-manager config fixed it without any `stylix.image` issues. thanks for help

Did you fully move the stylix inside home-manager or did you keep a part in nixos configuraiton ?

**Comment by knocking4thcylinder** [comment]
just added `stylix.targets.nixvim.enable = false` to home-manager

**Comment by knocking4thcylinder** [comment]
Other things still are set up as a nixos module

**Comment by danth** [comment]
This is because NixVim itself can be used at either the NixOS or Home Manager level, so you need to set the target options at the same level where you chose to install NixVim.

**Comment by noahfraiture** [comment]
> Other things still are set up as a nixos module

Ok thank you, I finally fixed mine, the issue was something else and the error was misleading. Doing as you said works perfectly
