### ISSUE TITLE
bug: hyprland changed shadow config

### ISSUE THREAD

**Issue by Ciflire** [danth/stylix#606]
the actual version gives an error in the decoration section, a recent commit changed the shadow configuration, the related commit is down below
https://github.com/hyprwm/Hyprland/commit/e4ab28b1fb063e5554c953c721779644ef6ada08

**Comment by nukdokplex** [comment]
it was too fast, hyprland in nixpkgs unstable is still not updated

**Comment by Ciflire** [comment]
Sry, should've specified that it was the actual git version, however the next version should pop this weekend. Also I believe the recommended way of using Hyprland is using the flake

**Comment by Ciflire** [comment]
I prefer the git version, it has the blue screen filter. Also tester when I have time
Again, sorry for the inconvenience
