### ISSUE TITLE
Hyprland <decoration:col.shadow> does not exist.

### ISSUE THREAD

**Issue by carettt** [danth/stylix#614]
Stylix uses the option `decoration."col.shadow"` to set the shadow colour with hyprland. With the recent update, the option is now: `decoration.shadow.color`.

**Comment by trueNAHO** [comment]
This change has already been refused:

- https://github.com/danth/stylix/pull/605
- https://github.com/danth/stylix/pull/608

However, consider reading https://github.com/danth/stylix/pull/605#issuecomment-2464077405.
