### ISSUE TITLE
Gnome 47 styling issues

### ISSUE THREAD

**Issue by musjj** [danth/stylix#618]
This is how it looks by default:
![image](https://github.com/user-attachments/assets/c48e5a52-e6fb-4ccd-9a36-f3e7a7c5e8dd)

This is how it looks with `stylix.targets.gnome.enable` enabled on the NixOS module:

![image](https://github.com/user-attachments/assets/db404c40-2ab5-45b0-b3e4-1270af0522d5)

This is how it looks by default on Gnome 46.1:

![image](https://github.com/user-attachments/assets/754f301c-5390-447a-a639-5812a3e5dbf6)

Anyone know what's causing this? I'm on `nixos-unstable` with Gnome 47 and I'm noticing that the repo pinned it for 46:

https://github.com/danth/stylix/blob/6863412636c8f2cb3b7360f747fbd020fbfddf68/flake.nix#L36

It looks like that Gnome updated the button layout for 47, so maybe there's a styling conflict?

**Comment by musjj** [comment]
I tried to update it to `47.1` in my fork, but the button colors ended up getting weird:

![image](https://github.com/user-attachments/assets/0a527b0a-6603-4963-9f39-d30a905f4558)

The only thing I changed in the patch is (due to an error):

```diff
- $selected_borders_color: transparentize(#{{base05-hex}}, 0.5);
+ $accent_borders_color: transparentize(#{{base05-hex}}, 0.5);
```

I tried to compare the patches against the associated upstream files, but I'm not noticing anything off. I wonder if there's a styling system change somewhere in the codebase.

One thing I'm noticing is that they have this `-st-*` colors:

```scss
$accent_borders_color: if($variant== 'light', st-darken(-st-accent-color, 15%), st-lighten(-st-accent-color, 15%));
```

But I'm not sure where it's coming from. Some assistance would be really appreciated here!

**Comment by danth** [comment]
Usually, after each release, I update the `gnome-shell` input in `flake.nix`, and then modify the new source code by hand to recreate the patches.

I haven't got around to doing this yet, so it's effectively still using the CSS from GNOME 46, but applied to the new GNOME 47 UI, hence the issues.

**Comment by musjj** [comment]
I actually tried to update the repo to Gnome 47, but there are these new [accent color](https://release.gnome.org/47) values that I'm not sure what to do about. For example, the button bg colors are now derived from `-st-accent-color` (which is why it looks weird in my second post), but I'm not sure how to customize them:

([`46.1`](https://github.com/GNOME/gnome-shell/blob/0d0aadf013f78a7f7f1dc984d0d812971864b934/data/theme/gnome-shell-sass/_common.scss#L120) -> [`47.1`](https://github.com/GNOME/gnome-shell/blob/83a88100034063856a87b2ac3c3497e49f074cb6/data/theme/gnome-shell-sass/_common.scss#L123))

```diff
-  @include button(normal, $c:$selected_bg_color, $tc:$selected_fg_color, $style: default);
+  @include button(normal, $c:-st-accent-color, $tc:-st-accent-fg-color, $style: default);
```

I wonder if you should just `sed` these values to the base16 colors.

**Comment by danth** [comment]
Regarding the accent colors, the [style guide](https://stylix.danth.me/styling.html#images) lists which colours each `base` "normally" corresponds to. Would that be sufficient?

Alternatively, we could consider disabling or hiding the accent color setting somehow, similar to how we currently handle the dark/light mode toggle.
