### ISSUE TITLE
hyprland.conf syntax change

### ISSUE THREAD

**Issue by cowboyai** [danth/stylix#622]
stylix is writing incorrect syntax to hyprland.conf for shadows

col.shadow = rgba(1a1a1aee)

is now:

shadow {
      enabled = true
      range = 4
      render_power = 3
      color = rgba(1a1a1aee)
    }

the old syntax displays as an error in hyprland

**Comment by trueNAHO** [comment]
Is this related to https://github.com/danth/stylix/pull/610?

**Comment by jaredmontoya** [comment]
it is

**Comment by trueNAHO** [comment]
Closing as duplicate: https://github.com/danth/stylix/pull/610.
