### ISSUE TITLE
tinted themeing repo no longer working

### ISSUE THREAD

**Issue by drishal** [danth/stylix#625]
As the title mentions, the tinted theming repo gives an error on trying to do a nixos rebuild switch, which did not used to happen before 

```nix
    stylix.base16Scheme = "${inputs.tt-schemes}/base16/everforest-dark-hard.yaml";
```
and for flake input
```nix
inputs.tt-schemes = {
      url = "github:tinted-theming/schemes";
      flake = false;
    };
  ```
  
  which gives the following error
  ```
         … while calling the 'head' builtin
         at /nix/store/0sxsfzswhjck7f4sbsvznz285s4i7y64-source/lib/attrsets.nix:1574:11:
         1573|         || pred here (elemAt values 1) (head values) then
         1574|           head values
             |           ^
         1575|         else

       … while evaluating the attribute 'value'
         at /nix/store/0sxsfzswhjck7f4sbsvznz285s4i7y64-source/lib/modules.nix:816:9:
          815|     in warnDeprecation opt //
          816|       { value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          817|         inherit (res.defsFinal') highestPrio;

       … while evaluating the option `system.build.toplevel':

       … while evaluating definitions from `/nix/store/0sxsfzswhjck7f4sbsvznz285s4i7y64-source/nixos/modules/system/activation/top-level.nix':

       … while evaluating the option `system.systemBuilderArgs':

       … while evaluating definitions from `/nix/store/0sxsfzswhjck7f4sbsvznz285s4i7y64-source/nixos/modules/system/activation/activatable-system.nix':

       … while evaluating the option `system.activationScripts.etc.text':

       … while evaluating definitions from `/nix/store/0sxsfzswhjck7f4sbsvznz285s4i7y64-source/nixos/modules/system/etc/etc-activation.nix':

       … while evaluating definitions from `/nix/store/0sxsfzswhjck7f4sbsvznz285s4i7y64-source/nixos/modules/system/etc/etc.nix':

       … while evaluating the option `environment.etc."brave/policies/managed/extra.json".source':

       … while evaluating definitions from `/nix/store/0sxsfzswhjck7f4sbsvznz285s4i7y64-source/nixos/modules/system/etc/etc.nix':

       … while evaluating the option `environment.etc."brave/policies/managed/extra.json".text':

       … while evaluating definitions from `/nix/store/0sxsfzswhjck7f4sbsvznz285s4i7y64-source/nixos/modules/programs/chromium.nix':

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: Error (base16.nix): Processing the input argument of the `mkSchemeAttrs` failed.
       Please consult https://github.com/SenchoPens/base16.nix/tree/main#%EF%B8%8F-troubleshooting
       builtins.toJSON of the parse result:
       {"author":"Sainnhe Park (https://github.com/sainnhe)","base00":"\"","base01":"\"","base02":"\"","base03":"\"","base04":"\"","base05":"\"","base06":"\"","base07":"\"","base08":"\"","base09":"\"","base0A":"\"","base0B":"\"","base0C":"\"","base0D":"\"","base0E":"\"","base0F":"\"","name":"Everforest Dark Hard","scheme":"Everforest Dark Hard","system":"base16","variant":"dark"}
 ```

**Comment by trueNAHO** [comment]
> As the title mentions, the tinted theming repo gives an error on trying to do a nixos rebuild switch, which did not used to happen before
>
> [...]
>
> ```nix
> inputs.tt-schemes = {
>       url = "github:tinted-theming/schemes";
>       flake = false;
>     };
> ```

Is this related to Stylix explicitly locking some of its tinted-theming inputs? [1] [2]

[1]: https://github.com/danth/stylix/blob/be94701ce7b746cb020e667f71492e398ed470f4/flake.nix#L68-L79
[2]: https://github.com/danth/stylix/blob/be94701ce7b746cb020e667f71492e398ed470f4/flake.nix#L68-L79

**Comment by drishal** [comment]
> > As the title mentions, the tinted theming repo gives an error on trying to do a nixos rebuild switch, which did not used to happen before
> > [...]
> > ```nix
> > inputs.tt-schemes = {
> >       url = "github:tinted-theming/schemes";
> >       flake = false;
> >     };
> > ```
> 
> Is this related to Stylix explicitly locking some of its tinted-theming inputs? [1](https://github.com/danth/stylix/blob/be94701ce7b746cb020e667f71492e398ed470f4/flake.nix#L68-L79) [2](https://github.com/danth/stylix/blob/be94701ce7b746cb020e667f71492e398ed470f4/flake.nix#L68-L79)

I don't think so, since it was working atleast upto the previous week when i had updated

**Comment by trueNAHO** [comment]
> > Is this related to Stylix explicitly locking some of its tinted-theming inputs? [1](https://github.com/danth/stylix/blob/be94701ce7b746cb020e667f71492e398ed470f4/flake.nix#L68-L79) [2](https://github.com/danth/stylix/blob/be94701ce7b746cb020e667f71492e398ed470f4/flake.nix#L68-L79)
>
> I don't think so, since it was working atleast upto the previous week when i had updated

Are you overriding (with `.follows`) any Stylix inputs with your `tt-schemes` input:

```nix
inputs.tt-schemes = {
  url = "github:tinted-theming/schemes";
  flake = false;
};
```

This may cause version incompatibilities.

**Comment by viicslen** [comment]
I'm having the same issue and I have not overridden any of the flake's inputs. The base16.nix module seems to be having the same issue unless declaring `use-idf = "auto"`

**Comment by drishal** [comment]
> I'm having the same issue and I have not overridden any of the flake's inputs. The base16.nix module seems to be having the same issue unless declaring `use-ifd = "auto"`

ah yes, I think stylix might need to specify this use ifd option as well

**Comment by trueNAHO** [comment]
I am unable to replicate this on commit 5ab1207b2fdeb5a022f2dd7cccf6be760f1b150f. Can you provide a minimal breaking example?

**Comment by pinksteven** [comment]
I'm pretty sure this is due to tinted theming appending # to every single color in commit [61058a8](https://github.com/tinted-theming/schemes/commit/61058a8d2e2bd4482b53d57a68feb56cdb991f0b)

**Comment by viicslen** [comment]
> I am unable to replicate this on commit [5ab1207](https://github.com/danth/stylix/commit/5ab1207b2fdeb5a022f2dd7cccf6be760f1b150f). Can you provide a minimal breaking example?
> 
> > The base16.nix module seems to be having the same issue unless declaring `use-ifd = "auto"`
> 
> From where is this option?

https://github.com/SenchoPens/base16.nix/tree/main#%EF%B8%8F-troubleshooting

https://github.com/SenchoPens/base16.nix/blob/c89c8123310257f3ddc04cc59aa4b5573c6d515f/README.md?plain=1#L241-L296


> I'm pretty sure this is due to tinted theming appending # to every single color in commit [61058a8](https://github.com/tinted-theming/schemes/commit/61058a8d2e2bd4482b53d57a68feb56cdb991f0b)

You are right, locked tt repo to one commit back and it started working again.

**Comment by trueNAHO** [comment]
> > I'm pretty sure this is due to tinted theming appending # to every single color in commit [61058a8](https://github.com/tinted-theming/schemes/commit/61058a8d2e2bd4482b53d57a68feb56cdb991f0b)
>
> You are right, locked tt repo to one commit back and it started working again.

Thanks for finding the culprit commit.

Considering that this breaking change eventually affects all Stylix users, it should be considered as a high priority issue. *Pinging @danth for this reason.*

Unfortunately, I don't have the bandwidth to resolve this issue right now. Feel free to submit a PR resolving this issue.

**Comment by pinksteven** [comment]
from taking a quick look this problem is more of a [base16.nix](https://github.com/SenchoPens/base16.nix) problem as it is used to parse the yaml files (i think). There is already an [issue](https://github.com/SenchoPens/base16.nix/issues/17) submitted there. It might be possible to fix this up in stylix itself, but i don't have a whole lot of nix experience

**Comment by SenchoPens** [comment]
Hi guys, I fixed it, please update stylix' base16 flake lock

**Comment by trueNAHO** [comment]
Does https://github.com/danth/stylix/pull/640 resolve the issue?

**Comment by drishal** [comment]
thanks, everything seems to be working fine

**Comment by arunoruto** [comment]
For those coming here from the 24.05 stable: you are probably in a deadlock where either stylix does not work by getting an error from this issue, or by trying out the master branch of stylix, you will encounter the issue #577.

You can update both nixpkgs and home-manager to 24.11 and set stylix to master. It will take some time to rebuild, but in the end, you should have a working config again!
