### ISSUE TITLE
A lot of new hyprland breaking changes

### ISSUE THREAD

**Issue by pective** [danth/stylix#630]
Hyprland changes more config options than col.shadow. I'll attach a screenshot of the config errors
![image](https://github.com/user-attachments/assets/6cd0111b-8d8a-42d1-b039-5d45788b62ac)

**Comment by trueNAHO** [comment]
> Hyprland changes more config options than col.shadow.

This affects Hyprland v45.0 that https://github.com/danth/stylix/pull/610 presumably updated to, right? In that case, feel free to submit a PR.

Unfortunately, I am currently unable to update Hyprland because I have to resolve some breaking changes on my end.

**Comment by kjkent** [comment]
@pective is it possible that it's your (non-stylix) hyprland config that's causing this? I had the same issue after updating, and it was because I had old-style config in my Hyprland, and changing:
```Nix
 drop_shadow = true;
 shadow_range = 4;
 shadow_render_power = 3;
```
to
```Nix
shadow = {
   enabled = true;
   range = 4;
   render_power = 3;
};
```
Cleared all the errors. Btw that's Nix syntax, native Hyprland is a bit different I think.

**Comment by pective** [comment]
@kjkent Yup, that fixed it! I didn't take into consideration that just changing the config would fix it, i thought it was stylix's fault. Thanks!
