### ISSUE TITLE
Error building on nixos

### ISSUE THREAD

**Issue by sadan4** [danth/stylix#637]
I was trying to setup stylix recently, but I ran into errors when rebuilding my system

after about two hours of searching I was not able to find anything on this issue

```
error:
       … while calling the 'seq' builtin
         at /nix/store/hfz1qqd0z8amlgn8qwich1dvkmldik36-source/lib/modules.nix:334:18:
          333|         options = checked options;
          334|         config = checked (removeAttrs config [ "_module" ]);
             |                  ^
          335|         _module = checked (config._module);

       … while calling the 'throw' builtin
         at /nix/store/hfz1qqd0z8amlgn8qwich1dvkmldik36-source/lib/modules.nix:310:18:
          309|                     ''
          310|             else throw baseMsg
             |                  ^
          311|         else null;

       error: The option `home-manager._type' does not exist. Definition values:
       - In `/nix/store/k6amv4549h6slpjaqy265hpz3xilwqgv-source/boxes/desktop/configuration.nix': "flake"
```

**Comment by Permafrozen** [comment]
Are you new to nixos? Do you mind showing me your config? (flake, and where ever you used the configuration)

> I was trying to setup stylix recently, but I ran into errors when rebuilding my system
> 
> after about two hours of searching I was not able to find anything on this issue
> 
> ```
> error:
>        … while calling the 'seq' builtin
>          at /nix/store/hfz1qqd0z8amlgn8qwich1dvkmldik36-source/lib/modules.nix:334:18:
>           333|         options = checked options;
>           334|         config = checked (removeAttrs config [ "_module" ]);
>              |                  ^
>           335|         _module = checked (config._module);
> 
>        … while calling the 'throw' builtin
>          at /nix/store/hfz1qqd0z8amlgn8qwich1dvkmldik36-source/lib/modules.nix:310:18:
>           309|                     ''
>           310|             else throw baseMsg
>              |                  ^
>           311|         else null;
> 
>        error: The option `home-manager._type' does not exist. Definition values:
>        - In `/nix/store/k6amv4549h6slpjaqy265hpz3xilwqgv-source/boxes/desktop/configuration.nix': "flake"
> ```

**Comment by sadan4** [comment]
> Do you mind showing me your config? (flake, and where ever you used the configuration)
> 
> > I was trying to setup stylix recently, but I ran into errors when rebuilding my system
> > after about two hours of searching I was not able to find anything on this issue

sorry about this

turns out in the imports of my configuration.nix I had accidentally added `inputs` and didn't manage to notice that.
