### ISSUE TITLE
Update to Stylix breaks generation

### ISSUE THREAD

**Issue by Noodlez1232** [danth/stylix#642]
It seems to be coming from generation of `stylix.base16Scheme`. Error is here:
```
       … while evaluating the option `home-manager.users.nathaniel.stylix.base16Scheme':

       … while evaluating the option `stylix.base16Scheme':

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: attribute 'name' missing
       at /nix/store/7y314p4mwz8kfr353146gcmjhiybf3zm-source/lib/util.nix:61:35:
           60|       scheme = raw.name or "untitled";
           61|       slug = raw.slug or (slugify raw.name);
             |                                   ^
           62|     }
```
This line is from `base16.nix`. This uses dynamic generation using `stylix.image`.

Here's a quick flake.nix you can use. It'll give you the error right away
use `nix run .#nixosConfigurations.test.config.system.build.vm -- -m 4G -smp 4`
<details>
<summary>flake.nix</summary>

```nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs?ref=nixos-unstable";
    home-manager.url = "github:nix-community/home-manager";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";
    stylix.url = "github:danth/stylix/master";
    stylix.inputs.nixpkgs.follows = "nixpkgs";
    stylix.inputs.home-manager.follows = "home-manager";
  };

  outputs = { self, nixpkgs, home-manager, stylix }: {
    nixosConfigurations.test = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        # ====
        # Stylix config
        # ====
        ({config, pkgs, ... }: {
          # Some sort of OMORI background
          stylix.enable = true;
          stylix.image = pkgs.fetchurl {
            name = "background";
            hash = "sha256-IDGfD7At03QDfK6HN9AL7+GSnrPkzmrYL1uUFcW1b4Q=";
            url = "https://www.whatspaper.com/wp-content/uploads/2021/08/whatspaper-147.jpg";
          };
          stylix.polarity = "dark";
        })

        # ====
        # Basic system setup
        # ====
        ({ config, lib, ... }: {
          users.users.test = {
            description = "Guest";
            hashedPassword = "";
            isNormalUser = true;
            extraGroups = [ "wheel" ];
          };
          security.sudo.wheelNeedsPassword = false;
          home-manager.users.test.home.stateVersion = config.system.nixos.release;
          
          # Enable the desktop
          services.displayManager.sddm.enable = true;
          services.xserver = {
            enable = true;
            desktopManager.plasma5.enable = true;
          };
        })

        stylix.nixosModules.stylix
        home-manager.nixosModules.home-manager
      ];
    };
  };
}

```

</details>

**Comment by jules-sommer** [comment]
This isn't exactly a solution, however, it seems to come from base16.nix and their recent commit @ [4e9b16c8b44958bc6bf46d99c3bb1b59c9c9c764](https://github.com/SenchoPens/base16.nix/commit/4e9b16c8b44958bc6bf46d99c3bb1b59c9c9c764)

Which appears to add the `slugify` function on which the error is occurring.

To fix this for now, I simply pinned my stylix and base16.nix versions to these versions below, which were the most recent two commits that were compatible together when pinned like this. Then with the line `stylix.inputs.base16.follows` we just instruct Nix to build stylix with our pinned version of base16.nix.

That will get your flake building at the very least. Otherwise, I didn't investigate what is actually going wrong inside the base16.nix `slugify` function or with the `raw.name` attribute.

```nix
stylix.url = "github:danth/stylix/5ab1207b2fdeb5a022f2dd7cccf6be760f1b150f";
stylix.inputs.base16.follows = "base16";
base16.url = "github:SenchoPens/base16.nix/665b3c6748534eb766c777298721cece9453fdae";
```

**Comment by Noodlez1232** [comment]
Yeah that works as a temporary fix. I think I do know the problem with upstream base16.nix though. Gonna do a fork and PR and see if it works.

**Comment by Noodlez1232** [comment]
Just gave a PR. Hopefully it will be fixed, but if not, you can use my fork with the branch `slugify-fix`. Then you can use the newest stylix

**Comment by trueNAHO** [comment]
Does https://github.com/danth/stylix/commit/4912f4db00bc931c7636d827e829faf01f6bf155 resolve the issue?

**Comment by jules-sommer** [comment]
> Does commit [4912f4d](https://github.com/danth/stylix/commit/4912f4db00bc931c7636d827e829faf01f6bf155) resolve the issue?

No, I was building with the master branch of Stylix when I encountered this issue, so I think that commit where the version was bumped actually was the cause for a recent commit in the base16.nix repo containing the newly added `slugify` function in question which seems to have broken something.

I will try referencing the fork containing the PR to base16.nix from @Noodlez1232 on Stylix commit [4912f4d](https://github.com/danth/stylix/commit/4912f4db00bc931c7636d827e829faf01f6bf155)

**Comment by dbeley** [comment]
> Just gave a PR. Hopefully it will be fixed, but if not, you can use my fork with the branch `slugify-fix`. Then you can use the newest stylix.
> 
> ```nix
> stylix.url = "github:danth/stylix";
> stylix.inputs.base16.follows = "base16";
> base16.url = "github:Noodlez1232/base16.nix/slugify-fix";
> ```

You can also directly use the PR from the base repo like

```nix
base16.url = "github:SenchoPens/base16.nix?ref=refs/pull/19/head"
```

**Comment by Noodlez1232** [comment]
@trueNAHO You should be able to update inputs, this issue is now fixed upstream

**Comment by Noodlez1232** [comment]
I will submit a PR right now, just give me about an hour I'm in uni right now.
