### ISSUE TITLE
unable to see fonts in rofi, as well as waybar on nixos unstable

### ISSUE THREAD

**Issue by DockterTeagle** [danth/stylix#650]
Howdy, as the title suggests nixpkgs released an update with regards to nerdfonts on nixpkgs unstable that seems to be the culprit behind my woes. currenly on nixpkgs unstable there is a problem where boxes will show up instead of fonts in waybar and rofi.

**Comment by i-am-logger** [comment]
as of today

![image](https://github.com/user-attachments/assets/fc8f964f-fb19-46c0-b5e8-fed14e0c6414)

**Comment by vendion** [comment]
After updating my config using the new namespace nerd-fonts I am running into an issue where Kitty wont launch because it cannot find the font files:

```nix
stylix = {
    enable = true;
    fonts = {
        monospace = {
            name = "GoMono Nerd Font";
            package = pkgs.nerd-fonts.go-mono;
        };
    };
};
```

Then when I launch Kitty I get the following:

```
fast_data_types.FreeTypeError: Failed to load face from path: /home/vendion/.nix-profile/share/fonts/truetype/NerdFonts/GoMonoNerdFontMono-Bold.ttf with error: cannot open resource
[0.129] Failed to convert descriptor to face for bold font
```

It seems that the directry structure also changed in this update/resturcture of `nerd-fonts`, as the actual font files are now under `$HOME/.nix-profile/share/fonts/truetype/NerdFonts/GoMono/`

**Comment by trueNAHO** [comment]
Is this issue out of Stylix's scope?

**Comment by DockterTeagle** [comment]
I think its not, as I think it is just checking a path change? I dont know stylix's codebase tho

**Comment by trueNAHO** [comment]
> I dont know stylix's codebase tho

For reference, Stylix does not reference `nerd`:

```console
$ git checkout --quiet d13ffb381c83b6139b9d67feff7addf18f8408fe && rg --hidden --ignore-case nerd

```

**Comment by DockterTeagle** [comment]
huh, so its the fault of the other packages then?(waybar and others)?

**Comment by trueNAHO** [comment]
> so its the fault of the other packages then?(waybar and others)?

Hard to say without further investigation.

AFAIK, Stylix sets the waybar font with:

https://github.com/danth/stylix/blob/d13ffb381c83b6139b9d67feff7addf18f8408fe/modules/waybar/hm.nix#L44-L45

**Comment by DockterTeagle** [comment]
I am unable to reproduce the full error without stylix, curently by setting the font manually, rofi works fine but waybar has a few icons missing, lmk how else I can help

**Comment by DockterTeagle** [comment]
it seems to not be how you are setting the waybar font but hopw you are setting global(?) fonts, I have rofi theming disabled ad well as waybar and i still get the error

**Comment by TheColorman** [comment]
I am not sure this is a Stylix issue. I get this issue in several programs after the namespace change, some of which are not managed by Stylix. All Stylix does in this case is add `stylix.fonts.packages` to `fonts.packages`. I don't see how Stylix could be in charge of where the individual apps decide to look for fonts.

@DockterTeagle what exactly do you do to get it to work outside of stylix? Do you still add the same fonts to `fonts.packages`?

**Comment by TheColorman** [comment]
Most programs load fonts using [`fontconfig`](https://search.nixos.org/packages?channel=unstable&show=fontconfig&from=0&size=50&sort=relevance&type=packages&query=fontconfig), including kitty and rofi. Fontconfig keeps track of all your fonts and their paths on the system. The new namespace change has moved around some fonts, and it seems (at least on my system) that the fontconfig cache hasn't been updated. That is, fontconfig has been providing programs with the wrong path to the system fonts.

You can manually reload the fontconfig cache using `fc-cache -r`. Can anyone that are still experiencing this see if that solves the problem?

> Tip: to check whether fontconfig is using the old paths, try opening kitty from a different terminal. It should tell you that it can't find the font file. Then run `fc-list` and see if the path kitty is complaining about. If it's in the list, your fontconfig cache is out of date.

I really would expect the cache to be refreshed by NixOS during a rebuild when the font packages change. Might have to upstream this.

**Comment by void4071** [comment]
> You can manually reload the fontconfig cache using `fc-cache -r`. Can anyone that are still experiencing this see if that solves the problem?

Was seeing similar with Alacritty and Terminator, but this appears to have worked for me. Thanks!

**Comment by vendion** [comment]
It appears that forcing a rebuild of fontconfig cache worked for me as well, I'm able to successfully launch kitty after doing `fc-cache -r`. It is weird that Nix wouldn't have done this automatically upon the rebuild, when you add or remove a font from your config it seems to update it for you.

**Comment by trueNAHO** [comment]
It seems like this is not a Stylix issue after all.

Thanks for the clarification, @TheColorman!

**Comment by DockterTeagle** [comment]
this did it for me thanks

**Comment by TheColorman** [comment]
I still don't have any font on my KDE login screen, so guess there's still some programs that don't like the font change, even after refreshing cache
