### ISSUE TITLE
`stylix.targets.neovim` does not exist even tho the docs say so

### ISSUE THREAD

**Issue by vol8** [danth/stylix#653]
I tried to disable `stylix.targets.neovim.enable` but it just spits out this error:

```
error: The option `stylix.targets.neovim' does not exist. Definition values:
- In `/nix/store/f152j4s89c04w21rja6ibzxr8x7s77h1-source/modules/stylix.nix':
      {
         enable = false;
      }
```
And if I try to rebuild it again after this error, this happens: 
```
error: cached failure of attribute 'nixosConfigurations.nixos.config'
```

Yeah I am unsure what is happening. 
And before someone asks, yes I have stylix added properly and it works without that neovim line.

**Comment by trueNAHO** [comment]
Do you mind explaining how you resolved your issue?

**Comment by vol8** [comment]
There was an issue that was already solved, I didn't found it first.
You have to add this to your home.nix:

```nix
home-manager.sharedModules = [{
    stylix.targets.neovim.enable = false;
}];
```
