### ISSUE TITLE
`stylix.imageScalingMode` has no effect in many places

### ISSUE THREAD

**Issue by justDeeevin** [danth/stylix#677]
Changing `stylix.imageScalingMode`, as far as I can tell, has _no effect_. Stylix does set the scaling options for apps that have them (e.g. plasma, swaylock), but, as far as I can tell, this doesn't respect the mode chosen with `stylix.imageScalingMode`.

**Comment by trueNAHO** [comment]
> Changing `stylix.imageScalingMode`, as far as I can tell, has _no effect_. Stylix does set the scaling options for apps that have them (e.g. plasma, swaylock), but, as far as I can tell, this doesn't respect the mode chosen with `stylix.imageScalingMode`.

This option was introduced in commit c760f63a44a9 ("stylix: add background image scaling option (#372)") and currently only supports swaylock:

- > currently this only applied sway, but should probably be applied to the other WM/DE also supported in stylix
  >
  > -- https://github.com/danth/stylix/pull/372#issue-2305958599

- > This will need to be followed up by setting the option for more programs, and perhaps documenting what each scaling mode does
  >
  > -- https://github.com/danth/stylix/pull/372#pullrequestreview-2093790959

Feel free to submit a PR to add support for the applications you are interested in.

**Comment by justDeeevin** [comment]
Only sway! wow... I'll get to work on a PR !!
