### ISSUE TITLE
Chromium either not theming entirely or getting incorrect colors

### ISSUE THREAD

**Issue by GideonWolfe** [danth/stylix#686]
Sorry that I can't provide more detailed information here, I'm 99% a Firefox user, but I keep `chromium` around for the odd case where a page is broken in FireFox.

I don't have any sort of custom `userChrome` or `userContent` for `chromium`, I just installed it and let `stylix` do its thing. The only other thing I have modifying styles is the [DarkReader](https://github.com/darkreader/darkreader/) plugin.

My theme (catppuccin mocha) does not consist of this burgundy/rust color, yet it is the main color for all context menus, dropdowns, highlighted text, etc. within the browser chrome. 

![image](https://github.com/user-attachments/assets/3979100f-5f9f-4d57-9a14-dc7982d01646)

As you can see, the tabs, search bar, text, etc. are all colored according to my theme. But the second I right click *anywhere* or open *any* sort of dropdown/context menu, I am presented with the colors shown above, which don't appear in my theme.

I have also noticed this behavior on another machine, but I thought that was because I may have messed it up myself. I can confidently say that this is a fresh install and I haven't tweaked the `chromium` styles here at all.

**Comment by danth** [comment]
Unfortunately, Chromium only lets us set a single color via policies, and it automatically decides the rest of its theme based on that color.

This could be improved using an extension, but that's more complicated as extensions need to be signed/verified before they are installed.

**Comment by GideonWolfe** [comment]
ah TIL, I suspected there was a good reason. All the more reason to stick to Firefox. Thanks for the awesome tool :smile:
