### ISSUE TITLE
Option to make modules opt-in

### ISSUE THREAD

**Issue by Lyndeno** [danth/stylix#7]
### Description

Right now this project edits the configs in a way that it is only written when a particular application is actually enabled. I was thinking it would be a good idea to add a switch to make each module opt in instead of opt out.

### Use case

I am thinking of writing a module for this project that themes vim-lightline.

Not everyone uses lightline, and it would be nice to make this opt-in nature standard such that they do not have to enable lightline if they do not wish.

I was thinking a global ```makeOptIn``` option which would require each module to be enabled separately. Or perhaps make certain modules opt-in, depending on what they need to configure to work properly.

A lightline module would likely have to configure a vim plugin with a custom package, thus automatically installing lightline. Being able to not opt-in to this would allow users to not install plugins they won't necessarily use.

**Comment by danth** [comment]
I'd like to keep a way to turn on relevant modules automatically - most users won't check the commits in every update to know when there are new modules to enable. A way to disable certain modules would be useful though, and as you mentioned there are some things which should only be enabled when the user chooses. We can add a list of modules in the README to make users aware of those which always need to be opted into.

I'd suggest creating an option like `stylix.targets.whatever.enable` for each module. The Lightline module would default to `false`, and for other modules, the default can be an expression like `programs.whatever.enable && stylix.autoEnable`. Users would be able to set `autoEnable = false` to make everything opt-in, while others can leave it on the default `true` to keep the current behaviour. Or perhaps `false` should be the default, however that would break any existing usage.

**Comment by FlorianFranzen** [comment]
I would still appreciate if the module could be loaded without it being activated for example unless I do something like `stylix.enable = true`. Right now just including the stylix module will cause the missing `stylix.image` option to through an error.

**Comment by danth** [comment]
What happens if you set `stylix.autoEnable = false`?
