### ISSUE TITLE
Evaluation fails with home-manager 22.11, and cannot disable mako target

### ISSUE THREAD

**Issue by mrcjkb** [danth/stylix#70]
Hi.

Since #65, I am unable to evaluate my NixOS configuration, as I am still on home-manager 22.11.

I [tried disabling the mako target](https://github.com/mrcjkb/nixfiles/blob/ca9fd7e36d7d856127e084ceae69b7af7e017dc9/home-manager-base/default.nix#L41) with both

```nix
home-manager.sharedModules = [{
    stylix.targets.mako.enable = false;
}];
```

and

```nix
home-manager.users.mrcjk = {
    stylix.targets.mako.enable = false;
};
```

[as described here](https://danth.github.io/stylix/options-hm.html), but to no avail.
I always end up with
```
building the system configuration...
error: The option `home-manager.users.mrcjk.services.mako' does not exist. Definition values:
       - In `/nix/store/l84b6hgjc6i9nsgg6mbxdgdf3ddc2pxv-modules/mako/hm.nix':
           {
             _type = "if";
             condition = false;
             content = {
               backgroundColor = "#212121";
           ..
```

**Comment by dwarfmaster** [comment]
I think the best thing to do would be to create a release-22.11 branch that tracks NixOS/home-manager 22.11, while master tracks the main branch of those project.

**Comment by danth** [comment]
I agree, there needs to be some support for the latest stable release, without holding back changes which require unstable.

I've created [`release-22.11`](https://github.com/danth/stylix/tree/release-22.11) with the Mako commit reverted.

**Comment by mrcjkb** [comment]
Thanks!
