### ISSUE TITLE
Bad default

### ISSUE THREAD

**Issue by Mikilio** [danth/stylix#705]
https://github.com/danth/stylix/blame/963e77a3a4fc2be670d5a9a6cbeb249b8a43808a/modules/nixvim/nixvim.nix#L13

This is a low priority issue. But I would like to point out that change for the sake of change is never good.

This new default has no benefits whatsoever above the previous. I figured out the idea sprang from #535  but that seems to be motivated simply by personal preference.

While increasing the support of stylix is good, needlessly changing defaults will just cause unnecessary debugging overload when old configurations cause unexpected results. (It did for me)

Nixvim itself has a colorscheme.base16 option, which it uses base16-nvim for. As such, for Nixvim that is the default.

More than fixing this, I would like to appeal to more scrutiny with regard to these changes. So it at least becomes clear why it was made.

**Comment by trueNAHO** [comment]
I agree. Here is the reasoning:

> > Ideally the color usage should be as close to [the upstream style guide](https://github.com/tinted-theming/base24/blob/master/styling.md#specific-colours-and-their-usages) as possible. [Our own style guide](https://stylix.danth.me/styling.html) currently just refers to that link when it comes to text editors. Unfortunately, the guide isn't very specific in some cases, such as the example with `this` and `self`, hence the differences as each plugin author has used their own preference.
> >
> > [...]
> >
> > According to the upstream guide, nether of these are totally correct - variables should be red and booleans should be yellow (unless [donovanglover]'s chosen scheme has non-standard colors).
>
> Until the style guide has been expanded [1], it won't hurt to provide a new colorscheme plugin. Once the VIM highlight groups are implemented in Stylix [1], we can replace both colorscheme plugins with the VIM highlight groups.
>
> [1]: https://github.com/danth/stylix/issues/249
>
> [NAHO, "neovim: use mini.base16 for colorscheme"](https://github.com/danth/stylix/pull/536#issuecomment-2323079532)

**Comment by Mikilio** [comment]
Ok, that seems satisfactory.

Just need to keep in mind that this could be a reason for neovim to break for some users.
