### ISSUE TITLE
Standard window border colour

### ISSUE THREAD

**Issue by danth** [danth/stylix#73]
Currently, various different colour combinations are used for borders:

https://github.com/danth/stylix/blob/8125194ab8e98a6704e8e2189ed77a4459a5d437/modules/sway/hm.nix#L8-L9

https://github.com/danth/stylix/blob/8125194ab8e98a6704e8e2189ed77a4459a5d437/modules/bspwm/hm.nix#L12-L13

https://github.com/danth/stylix/blob/8125194ab8e98a6704e8e2189ed77a4459a5d437/modules/mako/hm.nix#L13

**Comment by SomeGuyNamedMy** [comment]
slightly related, but while i was working on waybar i have also found that the base16 styling guide is not very helpful due to the guide mostly targeting text editors rather then general desktop applications, perhaps we could make creating our own style guide a long term goal?

**Comment by dwarfmaster** [comment]
That's ambitious but would help to keep consistence longer term.

**Comment by danth** [comment]
I agree, a style guide would be useful.

**Comment by SomeGuyNamedMy** [comment]
ive been thinking i might have a go at this this weekend, im thinking it might be a good idea to split the style guide by application type,(window manager, popus, text editors, general applications, etc)

**Comment by SomeGuyNamedMy** [comment]
opened up #90 to begin to address this, am looking for opinions on how we want to do this.

**Comment by SomeGuyNamedMy** [comment]
sorry about not being active recently, ive had a bunch of school work

**Comment by SomeGuyNamedMy** [comment]
in terms of groups of applications does anyone have any other types that they want added?

**Comment by danth** [comment]
The current groups should be enough; most apps will fit into the general category. For those which don't fit, like Plymouth, I don't think we need a style guide as there aren't any other similar programs.
