### ISSUE TITLE
Swaylock wrapper

### ISSUE THREAD

**Issue by danth** [danth/stylix#8]
### Description

Within my NixOS configuration I use a wrapper script for Swaylock to set the colors.

This should be merged into Stylix.

### Use case

Theming Swaylock :)

**Comment by Lyndeno** [comment]
I am having trouble getting this to apply. I should be able to just run ```swaylock``` in the terminal and have this theme correct?

**Comment by danth** [comment]
Yes. It's supposed to replace `swaylock` with a shell script.

`less "$(which swaylock)"` will display the script if it's installed, and a binary file otherwise.

**Comment by Lyndeno** [comment]
Interesting, seems to still be a binary

**Comment by danth** [comment]
Perhaps you have another overlay which adds a `swaylock` package? That could overwrite our script, if the other overlay is applied later.

**Comment by Lyndeno** [comment]
As far as I know the term "overlay" does not occur in my nixos config. I will dig deeper and see if any other input could be affecting it.

**Comment by danth** [comment]
I just checked, and Home Manager has an option for Swaylock now. Perhaps using that rather than a wrapper script would help.

**Comment by Lyndeno** [comment]
Worth a shot. It is worth noting that module only exists in home-manager master, and not release-22.05 version. Not sure if that presents a problem

**Comment by danth** [comment]
I think it's possible to check existence of the option and disable our module if it's not present.

**Comment by danth** [comment]
@Lyndeno I've edited the module. Can you try again?

**Comment by Lyndeno** [comment]
It works for me now, thanks!

**Comment by 0x715C** [comment]
Using home-manager/release-22.05 i get, ``error: The option `home-manager.users.${USER}.programs.swaylock' does not exist.``
