### ISSUE TITLE
Readme Show and Tell

### ISSUE THREAD

**Issue by Krutonium** [danth/stylix#80]
Right now the README describes the goals, but doesn't have any screenshots of it actually in use, which makes it hard to evaluate before actually trying it. May I suggest adding screenshots?

**Comment by danth** [comment]
Good idea, I'll add a screenshot of my own configuration.

**Comment by dwarfmaster** [comment]
I'd advise against commiting any screenshots to the repo though, since usually they weight a lot more than the files, and flakes need to clone the repo to work, resulting in a lot more downloads.

**Comment by danth** [comment]
I added a screenshot and a link to the configuration as a Gist. It would be nice to have a couple more screenshots of different environments; if anyone wants contribute, you can upload images without committing them to the repository by editing the file directly on GitHub.
