### ISSUE TITLE
fonts.drv causing link errors

### ISSUE THREAD

**Issue by duckpuppy** [danth/stylix#87]
```
error: builder for '/nix/store/wlrrlqfmyzkvdarm90dx83kg41a6sv55-fonts.drv' failed with exit code 1;
       last 1 log lines:
       > ln: failed to create symbolic link '/nix/store/5jgyddi839rx80rpv79p65p2lgmr1icy-fonts/Library/Fonts/Caskaydia Cove Nerd Font Complete ExtraLight Italic.otf': File exists
       For full logs, run 'nix log /nix/store/wlrrlqfmyzkvdarm90dx83kg41a6sv55-fonts.drv'.
```

Whenever I try to build my flake (nix-darwin config) I get an error about linking a font where the link already exists. I get this even if I don't specify a font configuration - in that case, the error refers to one of the default DejaVu fonts.

I've tried `nix-store --delete /nix/store/5jgyddi839rx80rpv79p65p2lgmr1icy-fonts`, which completes successfully. The error will still occur, though.

I'm at a loss as to how to debug this issue, but I do not otherwise specify any font options (nix-darwin or home-manager) anywhere in my config.

**Comment by duckpuppy** [comment]
I can reproduce this with this simplified flake (placing an image named `imperial_black.jpg` in the same folder as this flake is all that's needed):
```
# Lots of ideas taken from https://git.sr.ht/~misterio/nix-config/tree/main
{
  description = "System and Home Manager configs";

  inputs = rec {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    darwin = {
      url = "github:lnl7/nix-darwin";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    stylix.url = "github:danth/stylix";
  };

  outputs = inputs @ { self, nixpkgs, home-manager, darwin, ... }:
    {
      darwinConfigurations = {
        dantooine = darwin.lib.darwinSystem {
          modules = [
            inputs.home-manager.darwinModules.home-manager
            inputs.stylix.darwinModules.stylix
            {
              stylix.image = ./imperial_black.jpg;
            }
          ];
          system = "x86_64-darwin";
        };
      };
    };
}
```

**Comment by duckpuppy** [comment]
@lovesegfault I see that you filed the issue that ended with creation of the Darwin module - Are you seeing this error, and if so did you get past it?

**Comment by duckpuppy** [comment]
I'm closing this issue here as it's an upstream bug with nix-darwin.

**Comment by lovesegfault** [comment]
That's because they default to `dejavu_fonts` for all the fonts, which means it ends up repeated, and causes the issue.
