### ISSUE TITLE
Gnome Extensions App DOes Not launch

### ISSUE THREAD

**Issue by Lyndeno** [danth/stylix#88]
More details on NixOS/nixpkgs#220690

I am unsure on the fix.

**Comment by danth** [comment]
It looks like the `postFixup` phase from here:

https://github.com/NixOS/nixpkgs/blob/645bc49f34fa8eff95479f0345ff57e55b53437e/pkgs/desktops/gnome/core/gnome-shell/default.nix#L225-L230

Is being overridden here:

https://github.com/danth/stylix/blob/a1c5d01a40ca65335925974741020fe8b217b7bd/modules/gnome/nixos.nix#L27-L32

I'll try fixing this.
